epfl-lara/stainless

.larabot.conf
frontends/library/stainless/io/package.scala
frontends/library/stainless/lang/package.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala

This moves the import of annotations in the stainless.io package object to the top-level. In this specific case, Dotty prohibits imports and usage of annotations from within the same scope.

Fix annotation import in stainless library

---

core/src/sphinx/intro.rst

Stainless rejects the `decreases` contract because `101 - n` can be negative, like:
```
...
[  Info  ]  - Now considering 'body assertion' VC for M @14:30...
[Warning ]  => INVALID
[Warning ] Found counter-example:
[Warning ]   n: BigInt -> 102
...
```
or, with `--termination`,
```
...
[Warning ]  ==> INVALID: measure is not well-founded in M
[  Info  ] Result for M
[  Info  ]  => BROKEN (Decreases Processor) -> DecreasesFailed
...
```
So I'm afraid that we need to ensure the metrics non-negative, with `stainless.math.max`.
(stainless revision: f9aff1428512669ccd431b827a501094a45a62aa)

Fix the termination metrics of the 91 function

---

build.sbt

The generation of two sources was buggy if the path contained \U (character escape in the program).
This pull request fixes it.

Fixed Windows issues for c:\User repository

---

build.sbt
core/src/main/scala/stainless/MainHelpers.scala
core/src/main/scala/stainless/frontend/FrontendFactory.scala
frontends/scalac/src/it/scala/stainless/ComponentTestSuite.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/ScalaCompiler.scala
frontends/stainless-dotty/src/main/scala/stainless/frontends/dotc/DottyCompiler.scala

Further improvement toward Scastie integration. With this PR, the stainless library files are embedded in the produced jar file(s).
- The files are embedded in the default produced jar with `sbt package` is run. This means that the `assembly` plugin is not *required*. But do we want to be able to ship stainless with all its dependencies more easily (i.e. as a standalone binary)? If yes, it seems a reasonable thing to use. ([There seem to be some issues with assembly and stainless-dotty.](https://gist.github.com/mantognini/eb4a4b9de144bdd22943e3b5354eac9b))
- It is also possible to run stainless as of now, that is without having the library embedded in a jar (it will get read from another directory however, namely some `target` directory).
- You can use [this …

Jar library

---

build.sbt
core/src/main/scala/stainless/evaluators/CodeGenEvaluator.scala
core/src/main/scala/stainless/termination/ChainProcessor.scala
core/src/main/scala/stainless/termination/ControlFlowAnalysis.scala
core/src/main/scala/stainless/termination/DecreasesProcessor.scala
core/src/main/scala/stainless/termination/LoopProcessor.scala
core/src/main/scala/stainless/termination/RecursionProcessor.scala
core/src/main/scala/stainless/termination/RelationProcessor.scala
core/src/main/scala/stainless/termination/SelfCallsProcessor.scala
core/src/main/scala/stainless/termination/SolverProvider.scala
core/src/main/scala/stainless/termination/TerminationComponent.scala
core/src/main/scala/stainless/verification/VerificationChecker.scala

Adapt stainless to changes introduced in epfl-lara/inox#39. Doesn't compile as-is: `build.sbt` needs to be updated and refer to a newest version of inox.
`TerminationComponent` will be updated after #67 is merged (merge conflict anyway).

Update for new Timer API

---

frontends/benchmarks/extraction/ExtractAny.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala

The type `Any` was previously not extracted, which would yield the following error, when referencing it:
```
[ Error  ] foo$0 depends on missing dependencies: Any$0.
[Internal] Missing some nodes in Registry: Any$0
[Internal] Please inform the authors of Inox about this message
```
This seems to be what is currently making #77's test suite fail.

Add missing case for type `Any` in `dotc.CodeExtraction`

---

core/src/main/scala/stainless/MainHelpers.scala
core/src/main/scala/stainless/verification/VerificationChecker.scala

Built on top of #76 for testing purposes (the crash are much more frequent with the newest changes). This PR disables parallelism on Apple's OS to workaround z3 crashes (as far as I can tell). See Z3Prover/z3#1080 & #74.

Parallel off for macOS

---

core/src/main/scala/stainless/extraction/oo/TypeEncoding.scala

This fixes the bug originally described in #128, but not the one in https://github.com/epfl-lara/stainless/issues/128#issuecomment-349359953.

Fix a bug in a generated `assume` clause during TypeEncoding

---

core/src/main/scala/stainless/extraction/imperative/ImperativeCodeElimination.scala
frontends/benchmarks/imperative/valid/OldThis3.scala
frontends/benchmarks/imperative/valid/OldThis4.scala

Small patch to properly get rid of `old` in the `ImperativeCodeElimination` transformation.

Fix processing of `Old`

---

core/src/main/scala/stainless/Report.scala
core/src/main/scala/stainless/evaluators/EvaluatorAnalysis.scala
core/src/main/scala/stainless/evaluators/EvaluatorComponent.scala
core/src/main/scala/stainless/evaluators/EvaluatorReport.scala
core/src/main/scala/stainless/termination/TerminationAnalysis.scala
core/src/main/scala/stainless/termination/TerminationComponent.scala
core/src/main/scala/stainless/termination/TerminationReport.scala
core/src/main/scala/stainless/verification/VerificationAnalysis.scala
core/src/main/scala/stainless/verification/VerificationComponent.scala
core/src/main/scala/stainless/verification/VerificationReport.scala

Closes #125.
In a nutshell, now reports keep track of which functions were verified/evaluated/... to generate them. This way, we can remove old VC that no longer exists (and are not replaced by another one).

Fix reporting under --watch 

---

core/src/main/scala/stainless/MainHelpers.scala
core/src/main/scala/stainless/frontend/CallBackWithRegistry.scala
core/src/main/scala/stainless/utils/IncrementalComputationalGraph.scala
core/src/main/scala/stainless/utils/Registry.scala

Fixes #145.
This PR provides a quick patch for the `--watch` mode: the compiler is completely recreated when exceptions are caught.
An alternative patch would be to add `reset` methods to `Frontend`, `CallBack`, `Registry`, `ICG`, ... I feel using a `var` in the `main` is a good alternative.
In both case, this patch is somewhat imperfect as some VC will be generated/verified after an exception is caught. This is because of the `MainHelpers.par` usage in `VerificationChecker`. Fixing this would require an additional, non-trivial synchronisation mechanism.
This results in the following output:
```
stainless CrashInox.scala --watch
[ Error  ] Environment$0 depends on missing dependencies: Option$2.
[Internal] Missing some nodes in Registry: Option$2
[Internal] Please inform the authors of …
```

Robust watch: reset compiler upon error

---

build.sbt
core/src/main/scala/stainless/Report.scala
core/src/main/scala/stainless/verification/VerificationChecker.scala
core/src/sphinx/options.rst
frontends/common/src/it/scala/stainless/ExtractionSuite.scala
frontends/common/src/test/scala/stainless/RegistryTestSuite.scala
frontends/common/src/test/scala/stainless/TestContext.scala
frontends/common/src/test/scala/stainless/ast/ExplicitNumericPromotionSuite.scala
frontends/common/src/test/scala/stainless/ast/LibraryLookupSuite.scala
frontends/common/src/test/scala/stainless/ast/TupleExtractionSuite.scala
frontends/common/src/test/scala/stainless/verification/InliningSuite.scala
frontends/common/src/test/scala/stainless/verification/RegistryVerificationSuite.scala
frontends/scalac/src/it/scala/stainless/ComponentTestSuite.scala
frontends/scalac/src/it/scala/stainless/LibrarySuite.scala
frontends/scalac/src/it/scala/stainless/verification/VerificationSuite.scala

I suggest to enable *by default* termination *and* verification components. Explicitly writing `--verification` or `--termination` will disable the other component unless both options are present in the command line arguments.
Also, because the VC cache seems stable I think it makes sense to have it on all the time, except when otherwise stated (i.e. using `--vc-cache=false`).

command line options: update default values

---

frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala

Fixes NullPointerException because such trees have no symbol.
Addresses https://github.com/epfl-lara/stainless/issues/103#issuecomment-343167664.

Ignore top level literal

---

.larabot.conf
build.sbt
core/src/main/scala/stainless/frontend/package.scala
frontends/scalac/src/main/resources/scalac-plugin.xml
frontends/scalac/src/main/scala/stainless/frontends/scalac/StainlessPlugin.scala
project/assembly.sbt
project/build.properties
project/plugins.sbt
sbt-plugin/src/main/scala/ch/epfl/lara/sbt/stainless/StainlessPlugin.scala
sbt-plugin/src/sbt-test/sbt-plugin/simple/build.sbt
sbt-plugin/src/sbt-test/sbt-plugin/simple/failure/src/main/scala/BadPre1.scala
sbt-plugin/src/sbt-test/sbt-plugin/simple/project/TestPlugin.scala
sbt-plugin/src/sbt-test/sbt-plugin/simple/project/plugins.sbt
sbt-plugin/src/sbt-test/sbt-plugin/simple/success/src/main/scala/ADTInvariants1.scala
sbt-plugin/src/sbt-test/sbt-plugin/simple/test
version.sbt

This PR adds a sbt-stainless plugin. Please, read the commits message for details.
I expect this PR will fail to execute the scripted test because currently the sbt-stainless plugin requires an external solver to be installed (and I assume that will be missing on the machine running the PR validation). To fix this issue I need a repository to fetch the scalaz3 dependency.

sbt-stainless plugin

---

build.sbt
core/src/sphinx/installation.rst
project/plugins.sbt

This Sbt plugin is the standard way to make executable projects in Scala
and gives a few more options, like the way to pass JVM arguments or system
properties, in addition to working on all platforms, including Windows.
The `universal:packageBin` task can produce an archive that can be used to
distribute the jars and runner scripts on all platforms.
PS. I did not remove the old scripts that are generated on `compile`, but that should be eventually the case.

Use native packager to generate runner scripts.

---

core/src/sphinx/installation.rst

I couldn't run sphynx to validate the added documentation because `sbt-site` doesn't seem to work anymore. In particular, [these explanations](https://github.com/epfl-lara/stainless/blob/master/core/src/sphinx/installation.rst#building-stainless-documentation) in the documentation seem to be outdated (they don't work) and the build also seem to [hint that `sbt-site` was disabled](https://github.com/epfl-lara/stainless/blob/master/build.sbt#L61-L63).

Documented stainless sbt integration

---

core/src/main/scala/stainless/extraction/imperative/ImperativeCleanup.scala
frontends/benchmarks/imperative/valid/NoMutation.scala

Some `old` nodes are left behind after `ImperativeCodeElimination`
when they are used over a reference that is not mutated.
Close #215.

Cleanup leftover `old` nodes

---

core/src/main/scala/stainless/extraction/PartialFunctions.scala
frontends/benchmarks/verification/valid/TestPartialFunction3.scala
frontends/library/stainless/lang/PartialFunction.scala
frontends/scalac/src/it/scala/stainless/verification/VerificationSuite.scala

eg.
```scala
def test1 = PartialFunction[Option[String], Int] {
case Some(str) => 42
}
```
gets precondition:
```scala
x$ match {
case Some(str) => true
case _ => false
}
```

Infer precondition of partial functions yielded by inexhaustive pattern matches

---

build.sbt
core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala
sbt-plugin/src/main/scala/ch/epfl/lara/sbt/stainless/StainlessPlugin.scala

By adding the stainless-library to the managed source directories, IDEA can
properly import a project on which stainless is enabled.
This is relevant for the PR I'm about to open on the verified-2048 project (as it enables to import that project smoothly inside IDEA)

Added stainless-library to the managed source directories

---

core/src/main/scala/stainless/extraction/oo/AdtSpecialization.scala
core/src/main/scala/stainless/extraction/oo/Definitions.scala
core/src/main/scala/stainless/extraction/oo/Trees.scala
frontends/benchmarks/verification/invalid/ObjectInvariant.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala

This enables us to check the ADT invariant for case objects even if no one ever directly references the case object. Previously, this was not the case and could thus potentially lead to runtime errors.
Because the "constructor function" is marked with `@inline`, it will disappear in the resulting program.
This PR also fixes #239.

Replace reference to case object with a call to a constructor function

---

core/src/main/scala/stainless/verification/DefaultTactic.scala
core/src/main/scala/stainless/verification/VerificationChecker.scala
core/src/main/scala/stainless/verification/VerificationConditions.scala
frontends/benchmarks/verification/invalid/ADTInvariantCheck.scala

Previously, the following testcase would correctly report an
invalid ADT invariant for `fail` without `--check-models`,
but when setting the latter option, it would be reported as
unknown because the model would to a runtime error,
ie. `Model leads to runtime error: ADT invariant violation for Foo(0)`.
```scala
object test {
case class Foo(x: BigInt) {
require(x != 0)
}
def fail = Foo(0)
}
```
Fixes #237

Check model for invalid ADT invariants in a more careful way

---

core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala
core/src/main/scala/stainless/extraction/imperative/EffectsChecker.scala
core/src/main/scala/stainless/extraction/imperative/ImperativeCleanup.scala
core/src/main/scala/stainless/extraction/imperative/Trees.scala
core/src/main/scala/stainless/extraction/innerfuns/Trees.scala
core/src/sphinx/library.rst
frontends/benchmarks/extraction/invalid/Purity.scala
frontends/benchmarks/verification/invalid/ExternMut.scala
frontends/library/stainless/annotation/package.scala

Annotate such a function with `@pure` to assume otherwise.
This PR subsumes #250, and should either be merged instead of #250, or should be rebased on top of it once it gets merged.
Closes #244. Closes #245.

Assume `@extern` functions mutate their arguments

---

core/src/main/scala/stainless/codegen/runtime/GenericValues.scala
core/src/main/scala/stainless/verification/AssertionInjector.scala

* `a + b`: check that `a + b >= a`
* `a - b`: check that `b <= a`
* `a * b`: check that `a = 0` or `(a * b) / a = b`
* `a / b`: check that `b != 0` (that should be enough for unsigned division?)

Assertions for operations on unsigned bitvectors

---

build.sbt
core/src/main/scala/stainless/codegen/runtime/GenericValues.scala
core/src/main/scala/stainless/verification/AssertionInjector.scala

This might be useful for people who wants to depend on `stainless-core` while using a recent version of `cats` (like me).

Update circe to 0.10.0-M2 which bumps cats to 1.2.0

---

build.sbt
core/src/main/scala/stainless/ast/Expressions.scala
core/src/main/scala/stainless/extraction/oo/TypeEncoding.scala
frontends/benchmarks/termination/looping/Inconsistency5.scala
frontends/benchmarks/verification/valid/ADTInvariants4.scala
frontends/library/stainless/proof/package.scala

Following a quick discussion with @jad-hamza & @romac from yesterday.
The idea is that, hopefully, the solver can benefit from this change when `check { ... }` expression are combined (e.g. through conjunctions): when verifying the n-th check expression, the solver shouldn't have to re-verify the n-1 previous ones.
I however don't have concrete proof that this actually makes things faster.

Add holds on `check`

---

core/src/sphinx/Makefile

Running `make gh-pages` from the `core/src/sphinx/` directory will now build the documentation,
and upload it to the `gh-pages` branch of the repository, overwriting anything that was there
beforehand, which is okay since the documentation sources are properly versioned in the `master` branch.

Add `gh-pages` target to documentation Makefile.

---

core/src/main/scala/stainless/utils/Registry.scala

What do you think? This warning is a bit annoying when working with non-sealed classes

Remove warning for non-sealed classes/traits

---

core/src/main/scala/stainless/MainHelpers.scala
core/src/main/scala/stainless/extraction/ExtractionCaches.scala
core/src/main/scala/stainless/extraction/ExtractionPipeline.scala
core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala
core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala
core/src/main/scala/stainless/extraction/imperative/ImperativeCodeElimination.scala
core/src/main/scala/stainless/extraction/inlining/FunctionInlining.scala
core/src/main/scala/stainless/extraction/methods/Laws.scala
core/src/main/scala/stainless/extraction/methods/MethodLifting.scala
core/src/main/scala/stainless/extraction/methods/SuperCalls.scala
core/src/main/scala/stainless/extraction/methods/Trees.scala
core/src/main/scala/stainless/extraction/oo/AdtSpecialization.scala
core/src/main/scala/stainless/extraction/oo/ExtractionCaches.scala
core/src/main/scala/stainless/extraction/oo/ExtractionPipeline.scala
core/src/main/scala/stainless/extraction/oo/Trees.scala
core/src/main/scala/stainless/extraction/oo/TypeEncoding.scala
core/src/main/scala/stainless/extraction/package.scala
core/src/main/scala/stainless/extraction/utils/DebugPipeline.scala
core/src/main/scala/stainless/extraction/utils/SyntheticSorts.scala
core/src/main/scala/stainless/extraction/xlang/PartialFunctions.scala
core/src/main/scala/stainless/extraction/xlang/package.scala
core/src/main/scala/stainless/verification/PartialEvaluation.scala
core/src/main/scala/stainless/verification/VerificationComponent.scala
frontends/common/src/test/scala/stainless/RegistryTestSuite.scala
frontends/common/src/test/scala/stainless/TestContext.scala

Following discussions with @samarion, this pull request changes a bit the caches API
* The `ExtractionCache`'s used by `CachingPhase` now use the `TransformerContext` instead of `s.Symbols` for `CacheKey` computations
* Replace `DependencyKey` by a more generic `SetKey`
* Fix some cache issues (thanks @romac for the report of the cache issue in `Laws`)
* Fix minor bug in `Trees` (thanks @samarion)
Edit: As we discussed, `MethodLifting` needs to be adapted to the new cache API and key computation must be done in the `TransformerContext`, but I leave this for another time

Use TransformerContext in CacheKey computations

---

core/src/main/scala/stainless/ast/SymbolOps.scala
core/src/main/scala/stainless/extraction/ExtractionCaches.scala
core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala
core/src/main/scala/stainless/extraction/imperative/EffectsChecker.scala
core/src/main/scala/stainless/extraction/imperative/ImperativeCleanup.scala
core/src/main/scala/stainless/extraction/imperative/Trees.scala
core/src/main/scala/stainless/extraction/methods/DependencyGraph.scala
core/src/main/scala/stainless/extraction/methods/FieldAccessors.scala
core/src/main/scala/stainless/extraction/methods/MutabilityAnalysis.scala
core/src/main/scala/stainless/extraction/methods/Trees.scala
core/src/main/scala/stainless/extraction/methods/package.scala
core/src/main/scala/stainless/extraction/oo/ExtractionCaches.scala
core/src/main/scala/stainless/extraction/oo/SymbolOps.scala
core/src/main/scala/stainless/extraction/oo/Trees.scala
core/src/main/scala/stainless/extraction/package.scala
core/src/main/scala/stainless/extraction/utils/DebugPipeline.scala
core/src/main/scala/stainless/extraction/xlang/TreeSanitizer.scala
frontends/benchmarks/extraction/invalid/ExtendNonMutable.scala
frontends/benchmarks/extraction/invalid/NonMutableFunTypeParameter.scala
frontends/benchmarks/extraction/invalid/NonMutableTypeParameter.scala
frontends/benchmarks/extraction/valid/MutableTypeParameter.scala
frontends/benchmarks/imperative/invalid/SimpleImperative.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala
frontends/library/stainless/annotation.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala

This phase adds a flag `IsMutable` to classes that are mutable. Mutable classes are computed thanks to the following fixpoint. A class is mutable if it has:
* a setter, or
* a getter to a mutable type, or
* a mutable ancestor, or
* a mutable descendant, or
* a `@mutable` annotation.
In addition, there is now code that checks that:
* a mutable class cannot extend a non-sealed class not marked as `@mutable`.
* non-mutability of type parameters has to be respected when extending classes.
* non-mutability of type parameters has to be respected when doing `FunctionInvocation`'s
This PR also adds dependency edges from classes to their accessors, so that state is never lost in dependency computations.
Thanks @samarion for the help!

Setup MutabilityAnalysis phase for classes

---

core/src/main/scala/stainless/extraction/methods/MethodLifting.scala
frontends/benchmarks/verification/valid/BigIntMonoidLaws.scala

In a method's dispatcher, we now constrain forwarded arguments to
have the expected type, rather than just casting them to said type.
Not doing leads in some cases to invalid models where some argument's
model is of a totally unrelated type.
It is sound to use `assume` for this, as this is a constraint that
is guaranteed by both Scala's and our type system.

Fix soundness issue in MethodLifting

---

core/src/main/scala/stainless/extraction/methods/FieldAccessors.scala
core/src/main/scala/stainless/extraction/oo/RefinementLifting.scala
core/src/main/scala/stainless/extraction/xlang/TreeSanitizer.scala
frontends/benchmarks/imperative/invalid/HiddenEffect.scala
frontends/benchmarks/imperative/invalid/ImpureMethods.scala
frontends/benchmarks/imperative/invalid/MutableTrait.scala
frontends/benchmarks/imperative/valid/VarUpdate.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala

The inlining require having the inlined functions as dependencies in the cache. I put all dependencies for simplicity but we could reduce the dependencies to only the dependencies that could to be inlined.

Make FieldAccessors funCache use all dependencies

---

core/src/main/scala/stainless/extraction/methods/Sealing.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala

This enables inheritance of the ghost flag (and library) when overriding accessors and when creating fields for accessors in the `Sealing` phase.
PS: We don't need the `Final` flag here right?

Keep ghost/library flags when overriding methods

---

build.sbt

… which produces a (very) fat jar that can reasonably be distributed by itself. It only depends on the JRE and on of our supported (SMT-LIB-compatible) solvers being installed.
@samarion @romac 
Could you test this on your machines by running
```
$ sbt ";project stainless-scalac-standalone; assembly"
$ java -cp frontends/stainless-scalac-standalone/target/scala-2.11/stainless-scalac-standalone-0.1.0.jar stainless.Main frontends/benchmarks/verification/valid/Trees1.scala
```
from the stainless project root?
Next steps would include having another sbt task in the `stainless-scala-standalone` that fetches a supported Z3 release (e.g. from https://github.com/Z3Prover/z3/releases) and creates a tar ball from the assembly jar and the z3 binaries.

Add stainless-scalac-standalone build

---

build.sbt
core/src/sphinx/installation.rst
frontends/scalac/src/main/scala/stainless/frontends/scalac/ScalaCompiler.scala

Leaving it to `false` prevents the compiler from finding the reflection library, and triggers the following error:
> Error: object scala in compiler mirror not found.
On the other hand, setting it to `true` somehow breaks reflection when running tests.
We therefore use the `sbt-buildinfo` plugin to differentiate between the standard and the standalone builds.

Set embedded Scala compiler setting 'usejavacp' to true when building standalone JAR

---

core/src/main/scala/stainless/ast/Printers.scala
frontends/benchmarks/verification/valid/NaturalBuiltin.scala
frontends/benchmarks/verification/valid/Peano.scala
frontends/library/stainless/math/Nat.scala
frontends/library/stainless/math/package.scala

Also includes a change that prints function calls with non-alphanumeric identifiers as infix.
For example:
```scala
case class Nat(value: BigInt) {
def +(that: Nat): Nat = Nat(this.value + that.value)
}
Nat(0) + Nat(1) == Nat(2)
```
will be printed as written above, instead of as:
```scala
+(Nat(0), Nat(1)) == Nat(2)
```

Add `Nat` type to the library

---

core/src/main/scala/stainless/ast/Printers.scala

This fixes a bug in 065aac7a85cdd5ab09443f8723b0042d0452263d which would print all function calls as infix.

Fix printing of calls to infix operators

---

.sbtopts

See https://www.atlassian.com/blog/archives/codecache-is-full-compiler-has-been-disabled.

Increase and automatically flush code cache

---

core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala
core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala
core/src/main/scala/stainless/extraction/imperative/EffectsChecker.scala
core/src/main/scala/stainless/extraction/imperative/ImperativeCleanup.scala
core/src/main/scala/stainless/extraction/imperative/TransformerWithType.scala
core/src/main/scala/stainless/extraction/imperative/Trees.scala
core/src/main/scala/stainless/extraction/methods/MutabilityAnalyzer.scala
core/src/main/scala/stainless/utils/Serialization.scala
frontends/benchmarks/extraction/invalid/MapAliasing.scala
frontends/benchmarks/extraction/invalid/MutableMapUpdated.scala
frontends/benchmarks/imperative/valid/MutableMapInit.scala
frontends/benchmarks/imperative/valid/MutableMapUpdated.scala
frontends/benchmarks/imperative/valid/MutateMap.scala
frontends/benchmarks/imperative/valid/MutateMapElement.scala
frontends/benchmarks/imperative/valid/MutateNestedMapElement.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/ASTExtractors.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala
frontends/library/stainless/lang/MutableMap.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala

These are treated similarly to arrays and are transformed to normal maps in ImperativeCleanup
— @jad-hamza

Add MutableMapType support in imperative trees

---

core/src/main/scala/stainless/MainHelpers.scala
core/src/main/scala/stainless/frontend/BatchedCallBack.scala
core/src/main/scala/stainless/frontend/CallBack.scala
core/src/main/scala/stainless/frontend/package.scala
frontends/library/stainless/annotation/annotations.scala

Implement @romac's idea for keeping symbols.
At the moment writing keep forces the use of `BatchedCallBack`.
In `BatchedCallBack`, we filter all library symbols except those marked by `@keep(g)` for some `g` given in the command-line option `--keep=g1,g2,...`
— @jad-hamza 
See #476

Keep annotation and option to avoid filtering out library symbols

---

build.sbt
core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala
core/src/main/scala/stainless/extraction/imperative/GhostChecker.scala
core/src/main/scala/stainless/extraction/imperative/ImperativeCodeElimination.scala
core/src/main/scala/stainless/extraction/imperative/TransformerWithType.scala
core/src/main/scala/stainless/extraction/imperative/Trees.scala
core/src/main/scala/stainless/utils/Serialization.scala
frontends/benchmarks/imperative/valid/Snapshot.scala
frontends/benchmarks/imperative/valid/Snapshot2.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/ASTExtractors.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala
frontends/library/stainless/lang/package.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
frontends/stainless-dotty/src/it/scala/stainless/DottyExtractionSuite.scala

Depends on #399, thanks @romac for the tips.
The Snapshot tree can be used to save the state of a mutable object, so that we can refer to it at a later point of the code.
— @jad-hamza 
Original PR at #418

Add snapshot keyword for imperative code

---

frontends/benchmarks/verification/invalid/Equations1.scala
frontends/benchmarks/verification/invalid/Equations2.scala
frontends/benchmarks/verification/invalid/Equations3.scala
frontends/benchmarks/verification/valid/Equations.scala
frontends/library/stainless/equations/package.scala
frontends/library/stainless/lang/package.scala

This PR makes equations right-associative instead of left-associative to get better positions in reports.
(This assumes missing positions are fixed with https://github.com/epfl-lara/stainless/pull/340)
In this program
```scala
import stainless.equations._
object LineNumbers {
def f(x: BigInt, y: BigInt, z: BigInt, t: BigInt, b1: Boolean, b2: Boolean, b3: Boolean) = {
x ==| b1 |
y ==| b2 |
z ==| b3 |
t
}
}
```
the expression appears to be parsed as:
```scala
(((x ==| b1) |
(y ==| b2)) |
(z ==| b3)) |
t
```
Since every function invocation of `|` starts at line 5, we get the following report, which can make it difficult to understand which step of proof fails or takes longer than other steps.
```
[  Info  ]   ┌───────────────────┐
[  Info  ] ╔═╡ stainless summary …
```

Make equations go backwards for better line number reporting

---

build.sbt
core/src/main/scala/stainless/Context.scala
core/src/main/scala/stainless/MainHelpers.scala
core/src/main/scala/stainless/Reporter.scala
core/src/main/scala/stainless/verification/VCResultMessage.scala
core/src/main/scala/stainless/verification/VerificationChecker.scala
frontends/common/src/test/scala/stainless/TestContext.scala
frontends/scalac/src/it/scala/stainless/GhostRewriteSuite.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/StainlessPlugin.scala

Result:
Some more work is needed on the Inox side to avoid having duplicated output in the SBT console.
Fixes #434

Report positions when going through the compiler reporter from the sbt plugin

---

.gitignore
build.sbt
core/src/main/scala/stainless/Configuration.scala
core/src/main/scala/stainless/MainHelpers.scala

The file must be named `stainless.conf` or `.stainless.conf` and be a valid HOCON file.
It will be searched for recursively starting from the current
directory and walking up the directory hierarchy.
So, if one runs stainless from `/a/b/c`, and there is a config
file in any of `c`, `b` or `a`, the first of those is going to be
loaded.
For example, the config file could contain the following:
```
vc-cache = false
debug = [verification, trees]
timeout = 5
check-models = true
print-ids = true
```
This will translate to the following command line options:
```
--vc-cache=false --debug=verification,trees --timeout=5 --print-ids
```
Closes #465

Support for configuration file

---

core/src/main/scala/stainless/utils/Serialization.scala

This commit fixes a crash on example `AnonymousClasses3.scala` (due to a missing serialization code).

Add serialization code for LocalMethodInvocation

---

core/src/main/scala/stainless/extraction/induction/InductElimination.scala
core/src/main/scala/stainless/extraction/termination/Trees.scala
frontends/benchmarks/verification/valid/ListOperations.scala

This is needed until we merge the typechecker, as the injected measure throws
off the termination checker, and Stainless can currently already properly
infer the appropriate measure.

Disable measure injection in InductElimination

---

core/src/main/scala/stainless/extraction/imperative/EffectsChecker.scala
frontends/benchmarks/imperative/valid/TraitVar3.scala

Fixes https://github.com/epfl-lara/stainless/issues/413 by removing aliasing checks from accessors. Does this workaround make sense?

No EffectsChecker in accessors

---

core/src/main/scala/stainless/extraction/imperative/ImperativeCodeElimination.scala
frontends/benchmarks/imperative/valid/OldThis3.scala
frontends/benchmarks/imperative/valid/OldThis4.scala

(In conjunction with https://github.com/epfl-lara/inox/pull/99) Fixes https://github.com/epfl-lara/stainless/issues/532
I'm not sure what this code does, but it was throwing away the tuple https://github.com/epfl-lara/stainless/issues/532, and only keeping `FunctionInvocation`'s and `ApplyLetRec`'s. I replaced that part so that all expressions are kept, does that seem correct?

Prevent over-simplifications in ImperativeCodeElimination

---

core/src/main/scala/stainless/transformers/SimplifierWithPC.scala

I needed to fix https://github.com/epfl-lara/stainless/issues/546, but I'm not sure if that's the right approach, we now completely ignore the `assumeChecked` here (except for one case).

Make purity of requires and assertions depend on their bodies

---

frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala

Run on the example from https://github.com/epfl-lara/stainless/issues/549, this will print:
```
[Warning ] Dropped non-empty body of @extern function g.
```
Would that even help the user figuring out what's happening? Also, I'm afraid this warning will get annoying if you actually want to have non-empty `@extern` functions.

Emit warning when dropping the non-empty body of a user @extern function

---

core/src/main/scala/stainless/Component.scala
core/src/main/scala/stainless/ast/Deconstructors.scala
core/src/main/scala/stainless/ast/Definitions.scala
core/src/main/scala/stainless/extraction/methods/Laws.scala
core/src/main/scala/stainless/extraction/methods/Trees.scala
core/src/main/scala/stainless/frontend/BatchedCallBack.scala
core/src/main/scala/stainless/frontend/SplitCallBack.scala
core/src/main/scala/stainless/solvers/InoxEncoder.scala
core/src/main/scala/stainless/utils/CheckFilter.scala
core/src/main/scala/stainless/utils/LibraryFilter.scala
core/src/main/scala/stainless/utils/Serialization.scala
frontends/common/src/test/scala/stainless/ast/LawsLibrarySuite.scala
frontends/common/src/test/scala/stainless/ast/LibraryInheritanceSuite.scala

Removes the library flag to laws flagged as library that have non-library subclasses, in order to verify non-library case classes that extend library abstract classes.
Close #521

Removes @library flag on typeclasses which have non-library subclasses

---

core/src/main/scala/stainless/utils/StringUtils.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/ScalaCompiler.scala

This would occur when instantiating two or more anonymous classes within a function,
they would both get the same identifier because of how the Symbol=>Identifier cache
would work for scalac.
This might unfortunately cripple the watch mode, as identifiers
might now sometimes differ between runs whereas they wouldn't before, which was the
whole point of this previous attempt to normalize them based on their owner chain.
Dotty was unaffected as it relies on the unique symbol id generated by the compiler.

Fix bug where anonymous inner classes would have same id

---

bin/launcher.tmpl.sh
bin/package-standalone.sh

@gsps Is `cd` followed by `pwd` more robust than directly using `dirname`?
I added a call to `readlink` to follow symbolic links, in case someone makes a symbolic link pointing to the generated `stainless` script.

Follow symbolic links when searching for base directory

---

build.sbt

I had issues building stainless on windows because of `\` and `\u` characters in `extraClasspath` and `extraCompilerArguments`. This PR fixes the issue for me.

Use triple quotes and escape \u for extraClasspath and extraCompilerArguments

---

frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala

Asserts at the top-level would be ignored as well right?

Remove warnings for asserts in extern functions

---

core/src/main/scala/stainless/verification/DefaultTactic.scala

```scala
import stainless.collection._
import stainless.lang._
object InsertionSort {
def isSorted(l: List[BigInt]): Boolean = l match {
case Nil() => true
case Cons(x, Nil()) => true
case Cons(x, xs @ Cons(y, ys)) => x <= y && isSorted(xs)
}
def insert(x: BigInt, l: List[BigInt]): List[BigInt] = {
require(isSorted(l))
l match {
case Nil() => Cons(x, Nil())
case Cons(y, ys) =>
if (x < y) Cons(x, l)
else Cons(y, insert(x, ys))
}
} ensuring(res => isSorted(res))
}
```
In `insert`, this will now report postconditions lines 15, 17, and 18 instead of 12 for all branches.

Improve position reporting for postconditions

---

core/src/main/scala/stainless/ast/SymbolIdentifier.scala
frontends/benchmarks/extraction/valid/ToString.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/ScalaCompiler.scala

Doing so for methods such as `toString` would give us mismatched symbols corresponding to `java.lang.Object` instead of the topmost ancestor of the class where `toString` is overridden, which then prevents the override check and the method lifting phase from functioning correctly.
Fix #655

Do not consider built-in classes in override chain

---

core/src/main/scala/stainless/transformers/PartialEvaluator.scala
core/src/main/scala/stainless/transformers/SimplifierWithSolver.scala
frontends/benchmarks/typechecker/valid/PartialCompiler.scala
frontends/benchmarks/verification/valid/PartialCompiler.scala

Do not check model when invoking solver during partial evaluation 

---

frontends/scalac/src/main/scala/stainless/frontends/scalac/GhostAccessRewriter.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/StainlessPlugin.scala
sbt-plugin/src/main/scala/ch/epfl/lara/sbt/stainless/StainlessPlugin.scala

Only verification is disabled, so it is now possible to enable the plugin on the whole project, in order to  pull in the Stainless library and perform ghost elimination.

Setting `stainlessEnabled := false` keeps library sources and ghost elimination

---

core/src/main/scala/stainless/termination/DecreasesTransformer.scala

Because `DecreasesProcessor` did not initialize its `trees` early enough,
a null pointer exception would be raised when attempting to combine
the `SymbolTransformer` it is wrapped in within `TerminationComponent#lowering`
together with the lowering transformer of `VerificationComponent.`

Fix null pointer exception when running --eval

---

frontends/library/stainless/lang/Map.scala
frontends/library/stainless/lang/Set.scala
frontends/library/stainless/lang/package.scala

The other possibility would have been to remove the `AnyVal` on MapOps and SetOps but that would clutter the trees, so I figured it's better to just move `mkString` into the companion object itself.

Work around a bug in scalac which would crash the compiler

---

frontends/library/stainless/lang/Set.scala

Without static checks these operations cannot be executed at runtime, as `forall` yields an exception.

Use static checks for SetOps as they invoke forall

---

core/src/main/scala/stainless/MainHelpers.scala
core/src/main/scala/stainless/frontend/package.scala
core/src/main/scala/stainless/package.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/FragmentChecker.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/StainlessPlugin.scala

* Add an exception handler that hides the stack trace and prints in the file `stainless-debug.txt`
* Use this exception handler in the Stainless Plugin
* Add an option to print the stack trace when there is an error
* Minor error messages changes

Error reporting

---

.gitignore
core/src/main/scala/stainless/MainHelpers.scala
core/src/main/scala/stainless/frontend/BatchedCallBack.scala
core/src/main/scala/stainless/frontend/SplitCallBack.scala
core/src/main/scala/stainless/frontend/package.scala
core/src/main/scala/stainless/package.scala

* Move printing of symbols to `--debug=frontend`
* Move printing of trace to `--debug=frontend`
* Move `stainless-debug.txt` to `stainless-stack-trace.txt` (do you think we should even keep this file, since we have `--debug=frontend`?)

Rearrange debugging options

---

core/src/main/scala/stainless/verification/TypeChecker.scala

This removes the rule that duplicates trees for checking `TupleType` and `SigmaType` and instead adds some subtyping rules. (Some more rules need to be added, for instance for `SigmaType`'s and `PiType`'s)

Remove the tuple rule that duplicates VCs

---

core/src/main/scala/stainless/Report.scala
core/src/main/scala/stainless/frontend/SplitCallBack.scala
core/src/main/scala/stainless/termination/MeasureInference.scala
core/src/main/scala/stainless/utils/Canonization.scala
core/src/main/scala/stainless/verification/TypeChecker.scala
core/src/main/scala/stainless/verification/TypeCheckerDerivation.scala
core/src/main/scala/stainless/verification/VerificationComponent.scala
core/src/sphinx/gettingstarted.rst
core/src/sphinx/index.rst
core/src/sphinx/installation.rst
core/src/sphinx/neon.rst
core/src/sphinx/verification.rst

* Remove check that measure has good type at call site (this was making arguments of recursive functions being type-checked twice, and thus duplicating VCs)
* Add check that mutually recursive functions have the same measure type
* `SplitCallBack` now processes mutually recursive functions together
* Improve HTML output for type-checking derivation

Various improvements

---

core/src/main/scala/stainless/ast/Expressions.scala
core/src/main/scala/stainless/ast/TypeOps.scala
core/src/main/scala/stainless/extraction/utils/SyntheticSorts.scala
frontends/benchmarks/verification/valid/AdtSpecializationUnapply.scala
frontends/benchmarks/verification/valid/AdtSpecializationUnapply2.scala

This PR fixes an issue I ran into when trying to add support for some synthesized unapplies. The bug can also be triggered on master though, and I [included a test case](https://github.com/epfl-lara/stainless/compare/fix-unapplyAccessor-inst?expand=1#diff-2160f6987b6b86c1669d115880f761c0) demonstrating the underlying issue through ADT specialization. The suggested fix is minimal, but I'd be happy to hear whether @samarion sees any problem with it.
As to why the given test case fails:
Initially, AdtSpecialization creates an unapply for `B` whose return type is `Option[{v: A | v is C || v is D}]`. However, during `matchToIfThenElse` we end up instantiating `isEmpty` and `get` with `A` rather than the refinement type. That is, we end up with `isEmpty[A](ourUnapplyForB(a))`.
Later, in the …

Fix unapplyAccessor not instantiating with refinement type

---

build.sbt
frontends/benchmarks/verification/valid/BalancedParentheses.scala
frontends/benchmarks/verification/valid/ListMonad.scala
project/build.properties

Some typing errors in the benchmarks are now fixed, and the binary is now working thanks to the sbt downgrade (see https://github.com/epfl-lara/stainless/issues/793)

Fix Dotty test suite and binary

---

core/src/main/scala/stainless/extraction/oo/TypeEncoding.scala

TypeEncoding may drop `Unit`-typed expressions when wrapping them in an adaptation to `Object`:
```scala
object TypeEncodingEatsTrees {
def foo(b: Boolean): Unit = {
if (b) {
true
} else {
assert(false)
()
}
()
}
}
```
The problematic transformation step:
```scala
-------------Functions-------------
def foo(b: Boolean): Unit = {
val t: Any = if (b) {
true
} else {
assert(false)
()
}
val res: Any = t
val tmp: Any = res
()
}
Symbols after TypeEncoding
-------------Functions-------------
def foo(b: Boolean): Unit = {
val t: Object = if (b) {
Boolean(true)
} else {
Unit()
}
val res: Object = t
val tmp: Object = res
()
}
```
What's needed is a fix for `wrap` that's analogous to the changes to `unwrap` in #818. Could've noticed that right away, my bad.

Fix TypeEncoding losing side-effects when wrapping Unit-typed expression

---

core/src/main/scala/stainless/frontend/BatchedCallBack.scala
core/src/main/scala/stainless/frontend/SplitCallBack.scala
core/src/main/scala/stainless/frontend/package.scala
core/src/main/scala/stainless/verification/CoqEncoder.scala
core/src/main/scala/stainless/verification/CoqExpression.scala
core/src/main/scala/stainless/verification/TypeChecker.scala
core/src/main/scala/stainless/verification/TypeCheckerContext.scala
core/src/main/scala/stainless/verification/TypeCheckerDerivation.scala
core/src/main/scala/stainless/verification/VerificationConditions.scala
frontends/benchmarks/genc/ImageProcessing.scala

* More text in tooltips for the HTML derivation
* Safer VCKind assignment (we reset the VCKind when entering the value side of a `Let`)
* Don't generate VCs at all when all conjuncts are marked `@unchecked` (previously a `true` VC was generated)

Minor type-checker improvements

---

core/src/main/scala/stainless/ast/SymbolOps.scala
core/src/main/scala/stainless/extraction/innerfuns/FunctionClosure.scala
core/src/main/scala/stainless/termination/Strenghtener.scala
core/src/main/scala/stainless/verification/AssertionInjector.scala
core/src/main/scala/stainless/verification/ChooseInjector.scala
core/src/main/scala/stainless/verification/TypeChecker.scala
core/src/main/scala/stainless/verification/TypeCheckerContext.scala
frontends/benchmarks/imperative/valid/Array7.scala
frontends/benchmarks/imperative/valid/While4.scala

* Fix issue #893 (wrong type parameters substitutions in function closures)     
* Remove Let case in withPath to avoid introducing unnecessary specs below lets
* Fix issue where the same unique identifier appears twice in a formula (because of shared lets in specs)

Fix 893 + minor fixes

---

core/src/main/scala/stainless/package.scala
core/src/main/scala/stainless/utils/FileWatcher.scala

I'm trying to make it so that pressing Enter force reload in `watch` mode (`watch` mode doesn't seem to work on some file systems, this needs to be fixed separately)
I guess that will only work when parallelism is enabled? Should I pass directly the `multiThreadedExecutionContext` (even when parallelism is disabled?)

Use Enter key to force watch mode to reload

---

core/src/main/scala/stainless/utils/FileWatcher.scala

The `WatchService` doesn't seem to work when using a Windows IDE on a Windows file while running Stainless from Windows Subsystem for Linux. This PR removes the `WatchService` and watches the files' timestamps every 500ms. (The PR also fixes an issue with the `Enter` key which was not taken into account).

Watch files manually without WatchService

---

core/src/main/scala/stainless/extraction/imperative/ImperativeCodeElimination.scala
core/src/main/scala/stainless/extraction/innerfuns/FunctionClosure.scala
core/src/main/scala/stainless/genc/phases/Scala2IRPhase.scala
core/src/main/scala/stainless/verification/TypeChecker.scala

* Fix issue where application in scrutinee crashed GenC                    
* Add positions to error messages in GenC
* Swap order of arguments in FunctionClosure for dependent types
* Fix head of empty list issue in ImperativeCodeElimination
* Add some subtyping rules for arrays, bags, maps (without assuming covariance)

Bug fixes and minor improvements

---

frontends/benchmarks/extraction/valid/Arrays.scala
frontends/library/stainless/lang/package.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala

The `.updated` from implicits provided by `scala.Predef` returns an `ArraySeq[T]` instead of an `Array[T]`.
Thanks to @samarion and @gsps for the suggestions!

Fix extraction of Array.updated

---

core/src/main/scala/stainless/extraction/oo/TypeEncoding.scala
frontends/benchmarks/verification/valid/NothingTypeEncoding.scala

Closes #945.
This was the suggested solution by @samarion (if I understood him correctly).
Expressions of type `Nothing` are transform to `error[ExpectedType]` to avoid 
introducing a type predicate. The drawback of the solution is that we lose the 
expression itself, and hence all its effects.
﻿

Transform nothing typed expressions to errors in type encoding

---

core/src/main/scala/stainless/extraction/termination/InductElimination.scala
core/src/main/scala/stainless/extraction/termination/Trees.scala
core/src/main/scala/stainless/extraction/trace/Trees.scala

- Add a proper case object to represent the `@induct` annotation
- Remove `@induct` flag on the function and its parameters after `InductElimination` and ensure well-formedness
- Always replace existing measure with measure computed from `@induct` params, even when the type-checker is disabled

Add Induct case object for `@induct` annotation

---

core/src/main/scala/stainless/MainHelpers.scala
core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala
core/src/main/scala/stainless/package.scala
frontends/benchmarks/extraction/invalid/ArgumentAliasing.scala

For issue https://github.com/epfl-lara/stainless/issues/947
@samarion I tried your suggestion of using `Try(getTargets(e)).toOption.getOrElse(exprOps.variablesOf(arg).map(v => Target(v, None, Path.empty))))` to identify aliases. Did you then want to check whether a target of one argument is a prefix of a target of another argument?
For issue #947, this doesn't seem to work because the targets of `c1` are `Some(Target(c1, None, <empty>))` and the targets of `c2` are `Some(Target(c1, None, <empty>))`. Should `getTargets` on `c2` also return `c1`?
We might have the same issue with `getTargets` returns `None`, because `variablesOf` will not capture the transitive dependencies.

More checks of argument aliasing

---

core/src/main/scala/stainless/termination/ChainProcessor.scala
core/src/main/scala/stainless/termination/Strengthener.scala
core/src/main/scala/stainless/termination/StructuralSize.scala
frontends/scalac/src/it/scala/stainless/termination/TerminationSuite.scala

This solves #726. The problem is caused because we consider lexicographic ordering to give (j,j) < j and thus, measures given are (j,j,0) and (j,0). 
I changed this order and added a version of chain processor inference that handles the example. The version should infer correct measures for chain processor in the case without unfolding.

More principled measure inference for chain processor

---

core/src/main/scala/stainless/extraction/oo/RefinementLifting.scala
core/src/main/scala/stainless/extraction/xlang/TreeSanitizer.scala
core/src/main/scala/stainless/verification/TypeChecker.scala

Fix #992 
There was an assertion injected by `RefinementLifting` at the spec level (after the `let`, before the `decreases`), which made Stainless think `decreases` was part of the body

Prevent RefinementLifting from injecting assertions at the spec level

---

core/src/main/scala/stainless/extraction/imperative/EffectsChecker.scala
core/src/main/scala/stainless/extraction/imperative/ReturnElimination.scala
core/src/main/scala/stainless/extraction/imperative/TransformerWithPC.scala
core/src/main/scala/stainless/extraction/imperative/TransformerWithType.scala
core/src/main/scala/stainless/extraction/imperative/Trees.scala
core/src/main/scala/stainless/extraction/inlining/FunctionInlining.scala
core/src/main/scala/stainless/extraction/xlang/TreeSanitizer.scala
core/src/main/scala/stainless/genc/phases/Scala2IRPhase.scala
frontends/benchmarks/imperative/invalid/Array3Opaque.scala
frontends/benchmarks/imperative/valid/Tutorial.scala
frontends/common/src/test/scala/stainless/verification/InliningOnceSuite.scala
frontends/library/stainless/lang/StaticChecks.scala
frontends/library/stainless/lang/package.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala

* Add dummy function calls for while loops to possibly make them @opaque and @inlineOnce
* Allow inlining (once) a recursive function in itself (useful in combination with `@opaque` when verifying a recursive function)
* Change test suite to adapt to the new semantics of inlining
* Hide bodies of `@opaque` functions when inlining (because their bodies get replaced by `choose` in `ChooseInjector`, after the `FunctionInlining` phase)

Add dummy function calls for while loops to possibly make them @opaque and @inlineOnce

---

core/src/main/scala/stainless/extraction/package.scala
core/src/main/scala/stainless/genc/CAST.scala
core/src/main/scala/stainless/genc/CASTDependencies.scala
core/src/main/scala/stainless/genc/CPrinter.scala
core/src/main/scala/stainless/genc/ir/ClassLifter.scala
core/src/main/scala/stainless/genc/ir/IR.scala
core/src/main/scala/stainless/genc/ir/IRPrinter.scala
core/src/main/scala/stainless/genc/ir/Referentiator.scala
core/src/main/scala/stainless/genc/ir/Transformer.scala
core/src/main/scala/stainless/genc/ir/Visitor.scala
core/src/main/scala/stainless/genc/phases/ComputeDependenciesPhase.scala
core/src/main/scala/stainless/genc/phases/ExtraOps.scala
core/src/main/scala/stainless/genc/phases/IR2CPhase.scala
core/src/main/scala/stainless/genc/phases/Scala2IRPhase.scala
frontends/benchmarks/genc/TwoOptions.scala
frontends/scalac/src/it/scala/stainless/GencSuite.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala

Fix https://github.com/epfl-lara/stainless/issues/1007
@deiruch Should we also prevent name mangling for `val`'s and `var`'s of `@export`'ed classes?

Add support for GenC @export annotation on types

---

core/src/main/scala/stainless/verification/TypeChecker.scala
frontends/scalac/src/it/scala/stainless/verification/TypeCheckerSuite.scala

cc: @romac 
Copied from channel discussion:
> I found an issue in the type-checker with the `letWitness` thing, where we bind `let x: T = e in body` as  `x: T  ; letWitness :  { letWitness : Unit | x = e }` in the type-checking context.
When `T` is a refinement type `{ x: _ | P(x) }`, the VC we generate looks like `P(x) ==> let x = e in cond` which is not good because the `let` comes after the usage of `x`.
If we change the order in the context to `letWitness :  { letWitness : Unit | x = e } ; x: T`, that's not good either because that makes the type-checking context not well-formed (it refers to `x` before `x` is bound).
> I was wondering whether we could come back to `P(x) ==> (x == e) ==> cond` in the VC generation, which was changed here: …

Revert let equality to implication

---

core/src/main/scala/stainless/verification/TypeChecker.scala
frontends/scalac/src/it/scala/stainless/verification/TypeCheckerSuite.scala
frontends/scalac/src/it/scala/stainless/verification/VerificationSuite.scala

I don't remember if there was a particular reason the refinement type checks were that high?

Change order of type-checker rules to generate one VC per branch

---

core/src/main/scala/stainless/extraction/imperative/Definitions.scala
core/src/main/scala/stainless/extraction/imperative/Trees.scala
frontends/common/src/test/scala/stainless/NonVarMutabilitySuite.scala

Closes #1014.
The original solution suggested by @samarion (thanks!) was that `getType` of `FieldAssignment` returns `Untyped` if the field is not annotated as `@var`. 
That approach was dropped in favour of an actual `ensureWellFormedFunction` check, as suggested by @romac.

Catch and fail on mutation of immutable fields

---

build.sbt
core/src/main/scala/stainless/MainHelpers.scala
core/src/main/scala/stainless/Reporter.scala
core/src/main/scala/stainless/package.scala
core/src/main/scala/stainless/utils/Serialization.scala
core/src/main/scala/stainless/verification/VerificationCache.scala
core/src/main/scala/stainless/verification/VerificationChecker.scala
core/src/main/scala/stainless/verification/VerificationComponent.scala
frontends/common/src/it/scala/stainless/verification/ComponentTestSuite.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/ScalaCompiler.scala

Opened this after closing https://github.com/epfl-lara/inox/pull/143
This PR displays a counter `Verified: 60 / 87` that gets updated on the same line.
What do people think? It's not very pretty with the global variables, but it seems to work :)
In  `SplitCallBack`, the denominator will increase with each new subprogram.
When starting a new watch cycle, we reset the counters.

Print verification progress but not verification conditions

---

core/src/main/scala/stainless/verification/AssertionInjector.scala

Fix https://github.com/epfl-lara/stainless/issues/994

No cast correctness check when there is only one constructor

---

frontends/stainless-noxt/src/main/scala/stainless/frontends/noxt/NoxtFrontend.scala

This is a small _maintenance_ PR that finally adds _all_ the flags the Rust frontend could possibly emit to the `FIXME` pattern match in `NoxtFrontend`.

Fix all case object flags in NoxtFrontend

---

core/src/main/scala/stainless/verification/TypeChecker.scala
frontends/scalac/src/it/scala/stainless/verification/ImperativeSuite.scala

Revert https://github.com/epfl-lara/stainless/pull/1011 (again)
Back to using `let` when building a VC.
@romac I think you were right, your example was probably about counter-example models and satisfiability queries (I need to double-check).
But having `let`'s is also useful to enable simplifications in Inox.
To address the issue I discussed in https://github.com/epfl-lara/stainless/pull/1011, I added an extra case:
```scala
case (x1, _) +: (_, LetEquality(x2: Variable, e2)) +: _ if x1.id == x2.id =>
let(x2.toVal, e2, vcFromContext(l.tail.tail, e))
```

Rerevert to using lets in VCs for satisfiability queries and Inox simplifications

---

build.sbt

That should make the non-incremental Z3 solvers work better.

Bump Inox version (checkAssumptions fix for Z3)

---

core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala
core/src/main/scala/stainless/extraction/imperative/EffectsChecker.scala
core/src/main/scala/stainless/extraction/imperative/GhostChecker.scala
core/src/main/scala/stainless/extraction/imperative/ImperativeCodeElimination.scala
core/src/main/scala/stainless/extraction/imperative/ReturnElimination.scala
core/src/main/scala/stainless/extraction/imperative/TransformerWithType.scala
core/src/main/scala/stainless/extraction/imperative/Trees.scala
core/src/main/scala/stainless/utils/Serialization.scala
frontends/benchmarks/imperative/invalid/FreshCopy.scala
frontends/benchmarks/imperative/valid/FreshCopy.scala
frontends/benchmarks/imperative/valid/FreshCopy2.scala
frontends/benchmarks/imperative/valid/FreshCopy3.scala
frontends/library/stainless/lang/package.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala

This PR adds a new primitive operation (as a tree) to Stainless. The new operation called `freshCopy` (naming ist still wip, your suggestion is welcome) is an exact duplicate of `snapshot` except that it can be used outside of the `@ghost` context.
There is no Scala code extraction for the primitive for now, because it is used via the Rust frontend. There, it solves a problem with AntiAliasing https://github.com/epfl-lara/rust-stainless/issues/154.

Add fresh copy primitive

---

core/src/main/scala/stainless/extraction/oo/TypeEncoding.scala

Fix https://github.com/epfl-lara/stainless/issues/1044 (thanks @samarion).
I cannot add the example from the issue because the mismatch in types is now caught before.

ArrayLength requires Int type during TypeEncoding

---

build.sbt
core/src/main/scala/stainless/ast/Definitions.scala
core/src/main/scala/stainless/extraction/inlining/FunctionInlining.scala

@samarion Is `simplestValue` for arrays ok here? Or do we need to check the base type is non-empty?

Simplest value API + inlined precondition numbering

---

build.sbt
core/src/main/scala/stainless/utils/RustInteropGenerator.scala

To make Inox completely frontend-independent, the tool that generates AST trees for Rust is moved to Stainless.
This is the dual of https://github.com/epfl-lara/inox/pull/155.

Move Rust interop generator from Inox

---

core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala
frontends/benchmarks/imperative/valid/CastCorrectness.scala

Closes #1070.
- Add test case for rewritings bug.
- Filter out immutable ValDefs from rewritings.

Imperative rewritings bug in pattern match

---

core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala
core/src/main/scala/stainless/extraction/imperative/EffectsChecker.scala

A new solution for the problem in https://github.com/epfl-lara/stainless/pull/1033/files#diff-94338a6a254a8818b64bec4aca058a1097dadc8a142418a53fa842b44024e7ecR9-R13. The previous solution was: https://github.com/epfl-lara/stainless/pull/1033/files#diff-8e88ff59f4e5533bd8fa25ed53c11010adbe901f39faa5647962bb39fdf45548R395-R39 which is not generally correct.

Compute targets of a fresh LetVar

---

core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala
core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala
core/src/main/scala/stainless/extraction/inlining/FunctionInlining.scala
frontends/benchmarks/imperative/valid/Issue1111.scala
frontends/benchmarks/imperative/valid/WrappedArray.scala

Fix #1111
I didn't handle the `LetVar` and `Block` cases, but this seems enough to fix #1111, and a similar issue I was having (see file `WrappedArray.scala`, because we were missing let bindings in (array and map) accessors too.

Add bindings when computing targets

---

core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala
core/src/main/scala/stainless/extraction/inlining/FunctionInlining.scala
core/src/main/scala/stainless/extraction/methods/FieldAccessors.scala
core/src/main/scala/stainless/genc/LeonInlining.scala
core/src/main/scala/stainless/genc/ir/IR.scala
core/src/main/scala/stainless/genc/ir/Transformer.scala
core/src/main/scala/stainless/genc/phases/IR2CPhase.scala
core/src/main/scala/stainless/genc/phases/Scala2IRPhase.scala
frontends/benchmarks/imperative/valid/LetTargets.scala
frontends/benchmarks/verification/invalid/InliningUnchecked.scala
frontends/benchmarks/verification/invalid/InliningUnchecked2.scala

The example `LetTargets` is failing in the current master branch, because the computation of targets in let expressions duplicates the `path` (once for the bound expression `e`, and once for the body `b`). We get targets which are not well-formed.

Fix computation of targets in let expressions

---

core/src/main/scala/stainless/genc/CAST.scala
core/src/main/scala/stainless/genc/CPrinter.scala
core/src/main/scala/stainless/genc/GenCComponent.scala
core/src/main/scala/stainless/genc/ir/IR.scala
core/src/main/scala/stainless/genc/ir/IRPrinter.scala
core/src/main/scala/stainless/genc/package.scala
core/src/main/scala/stainless/genc/phases/ComputeDependenciesPhase.scala
core/src/main/scala/stainless/genc/phases/ExtraOps.scala
core/src/main/scala/stainless/genc/phases/Scala2IRPhase.scala
core/src/sphinx/genc.rst
frontends/benchmarks/genc/ArgumentsEffects.scala
frontends/benchmarks/genc/FixedArray.scala
frontends/benchmarks/genc/Global.scala
frontends/benchmarks/genc/GlobalUninitialized.scala
frontends/benchmarks/genc/ImageProcessing.scala
frontends/benchmarks/genc/LZWa.scala
frontends/benchmarks/genc/LZWb.scala
frontends/benchmarks/genc/Nested.scala
frontends/benchmarks/genc/Normalisation.scala
frontends/benchmarks/genc/Pointer.scala
frontends/benchmarks/genc/Return.scala
frontends/benchmarks/genc/StateTest.scala
frontends/benchmarks/genc/TwoOptions.scala
frontends/benchmarks/genc/Unsigned.scala
frontends/benchmarks/genc/WhileInLet.scala
frontends/benchmarks/imperative/valid/LetTargets.scala
frontends/library/stainless/annotation/annotations.scala
frontends/library/stainless/annotation/cCode.scala
frontends/library/stainless/io/FileInputStream.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala

Fix #1126 and #1127
* `@export` becomes `@cCode.export`
* `@cCode.static` can be used on fields of global classes
* `@cCode.drop` implies `@extern`

Reorganize GenC annotations

---

core/src/main/scala/stainless/genc/CAST.scala
core/src/main/scala/stainless/genc/CPrinter.scala
core/src/main/scala/stainless/genc/ir/IR.scala
core/src/main/scala/stainless/genc/ir/Referentiator.scala
core/src/main/scala/stainless/genc/ir/Transformer.scala
core/src/main/scala/stainless/genc/package.scala
core/src/main/scala/stainless/genc/phases/IR2CPhase.scala
core/src/main/scala/stainless/genc/phases/Scala2IRPhase.scala
frontends/library/stainless/annotation/cCode.scala

* Add `@cCode.volatile` annotation for global variables
* Avoid pointers in global variables in GenC

GenC improvements

---

core/src/main/scala/stainless/extraction/imperative/EffectElaboration.scala
core/src/main/scala/stainless/extraction/imperative/HeapASTExtractors.scala
core/src/main/scala/stainless/extraction/imperative/Trees.scala
frontends/benchmarks/full-imperative/invalid/HeapEvalIsHypothetical.scala
frontends/benchmarks/full-imperative/invalid/HeapUnchangedInvalid.scala
frontends/benchmarks/full-imperative/valid/FirstClassHeap.scala
frontends/library/stainless/lang/package.scala

Exposes `Heap` in the standard library which allows explicit manipulation of different heap states. In particular `Heap.get` returns the current state, `Heap.unchanged(objs, heap1, heap2)` returns true whenever `heap1` and `heap2` are equal on all objects in `objs`, and `Heap#eval(e)` evaluates expression `e` in the context of the given heap.

Add first class heap representation

---

core/src/main/scala/stainless/extraction/imperative/EffectElaboration.scala
core/src/main/scala/stainless/extraction/imperative/HeapASTExtractors.scala
core/src/main/scala/stainless/extraction/imperative/package.scala
frontends/benchmarks/full-imperative/valid/AsHeapRefSet.scala
frontends/library/stainless/lang/package.scala

Adds the `asRefs` extension method that allows us to convert `Set[T <: AnyHeapRef]` to `Set[AnyHeapRef]`, working around the invariance of `Set[T]`. This is useful to deal with reads and modifies clauses. During lowering in the full-imperative phase the new method is erased, simplifying proofs. This is sound, because all types inheriting from `AnyHeapRef` are erased to `HeapRef` anyways (as is `AnyHeapRef` itself, of course).

Improve heap ref set handling

---

core/src/main/scala/stainless/extraction/imperative/EffectElaboration.scala
frontends/benchmarks/full-imperative/valid/NodeCycle.scala

Adds an example that exemplifies inductive proofs on the heap. Also includes some changes to `EffectElaboration` to avoid heap contract checks at call sites where any reads and modifications are allowed.

Add NodeCycle example

---

core/src/main/scala/stainless/extraction/imperative/EffectElaboration.scala
frontends/benchmarks/full-imperative/invalid/HeapGetProjectsReads.scala
frontends/benchmarks/full-imperative/invalid/UnsoundReadsFrameBug.scala
frontends/benchmarks/full-imperative/valid/TreeImmutMap.scala
frontends/benchmarks/full-imperative/valid/TreeImmutMapGeneric.scala
frontends/scalac/src/it/scala/stainless/verification/FullImperativeSuite.scala

Two distinct bugs (see commits and test cases witness issue before the changes).

Fix unsoundness with HeapGet and reads-frame assumption on heap-modifying functions

---

core/src/main/scala/stainless/ast/Deconstructors.scala
core/src/main/scala/stainless/ast/Definitions.scala
core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala
core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala
core/src/main/scala/stainless/genc/LeonInlining.scala
core/src/main/scala/stainless/genc/phases/IR2CPhase.scala
core/src/main/scala/stainless/solvers/InoxEncoder.scala
core/src/main/scala/stainless/utils/Serialization.scala
core/src/main/scala/stainless/verification/TypeChecker.scala
frontends/library/stainless/lang/package.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala

* Less casts and more freshening in imperative phase
* Add SplitAnd tree (&&&) to split verification conditions

Less casts in imperative phase, more freshening of local variables, and add SplitAnd tree

---

build.sbt
core/src/main/scala/stainless/MainHelpers.scala
core/src/main/scala/stainless/verification/VerificationAnalysis.scala
core/src/main/scala/stainless/verification/VerificationChecker.scala
core/src/main/scala/stainless/verification/VerificationConditions.scala

The second change allows the `Solver` object to be garbage-collected while `checkVCs` is running.

Updating Inox and removing Solver reference from VCResult objects

---

bin/launcher-cygwin-noscalaz3.tmpl.sh
bin/launcher-noscalaz3.tmpl.bat
bin/launcher-noscalaz3.tmpl.sh
bin/launcher.tmpl.sh
bin/package-standalone.sh
frontends/dotty/src/main/scala/stainless/frontends/dotc/DottyCompiler.scala

* Upgraded Z3 to 4.8.14 to be in-sync with ScalaZ3
* Removed old ScalaZ3 jars for macOS. As such macOS builds are not shipped with ScalaZ3
* Added standalone build for Windows (without shipping ScalaZ3)
* Small tweak in the `stainless.sh` script to allow users to pass extra arguments to the JVM.
For instance, if we would like to increase the heap size to 10G and stack size to 20M, we can do something as follows:
```
export JAVA_OPTS="-Xms10G -Xss20M"
./stainless-dotty-standalone/stainless.sh <rest>
```

Changes related to build for standalone Stainless

---

core/src/main/scala/stainless/Component.scala
core/src/main/scala/stainless/MainHelpers.scala
core/src/main/scala/stainless/frontend/package.scala
core/src/main/scala/stainless/genc/GenCComponent.scala
core/src/main/scala/stainless/genc/GenerateC.scala
core/src/main/scala/stainless/testgen/GenCTestGen.scala
core/src/main/scala/stainless/testgen/GenCTestGenComponent.scala
core/src/main/scala/stainless/testgen/ScalaTestGen.scala
core/src/main/scala/stainless/testgen/ScalaTestGenComponent.scala
core/src/main/scala/stainless/testgen/XLangTestGen.scala
core/src/main/scala/stainless/testgen/package.scala
core/src/main/scala/stainless/verification/VerificationComponent.scala

Add two new phases that attempts in creating test cases from reported counter-examples, namely `--testgen` (outputs Scala code) and `--genc-testgen` (outputs C code)

Experimental test cases generation

---

build.sbt

We apparently duplicated the content of ScalaZ3 jar within the Stainless jar.

Do not duplicate ScalaZ3 jar (for standalone builds)

---

core/src/main/scala/stainless/package.scala
core/src/main/scala/stainless/verification/VerificationChecker.scala

The VCs were actually not checked in parallel due to the use of `Future.successful` (eager) instead of `Future.apply` (maybe on purpose?).
It also enables parallelism back for macOS (as it seems the problem was caused by https://github.com/Z3Prover/z3/issues/1080, which is now addressed)

VC checking in parallel

---

core/src/main/scala/stainless/genc/CPrinter.scala
core/src/main/scala/stainless/genc/package.scala

Unexported functions are only visible to the `stainless.c` translation unit. We can annotate them `static`. 
This enables C compilers to perform more optimizations: for instance, we get a ~20% speedup on the QOI encoder benchmark.

GenC: annotate unexported function as static

---

core/src/main/scala/stainless/extraction/innerfuns/FunctionClosure.scala
frontends/benchmarks/verification/unchecked/NothingTypeEncoding.scala
frontends/benchmarks/verification/valid/InnerFunctions.scala
frontends/common/src/test/scala/stainless/ast/FunctionClosureSuite.scala

Addresses #1259
Edit: marked as a draft as I've found some bugs (that seem to be related to not taking into account function specifications)
Edit 2: the bug I've encountered has nothing to do with this PR... so I'm going to re-ready it (I'll try to fix the big in a separate PR).

Avoid unnecessary capture of PC variables when hoisting functions

---

build.sbt
core/src/main/scala/stainless/extraction/imperative/ReturnElimination.scala
core/src/main/scala/stainless/extraction/inlining/ChooseInjector.scala
core/src/main/scala/stainless/extraction/inlining/FunctionSpecialization.scala
core/src/main/scala/stainless/extraction/innerclasses/InnerClasses.scala
core/src/main/scala/stainless/extraction/oo/RefinementLifting.scala
core/src/main/scala/stainless/extraction/oo/TypeEncoding.scala
core/src/main/scala/stainless/extraction/trace/Trace.scala
core/src/main/scala/stainless/termination/ChainProcessor.scala
core/src/main/scala/stainless/termination/MeasureInference.scala
core/src/main/scala/stainless/transformers/PartialEvaluator.scala
core/src/main/scala/stainless/verification/ChooseInjector.scala
core/src/main/scala/stainless/verification/CoqEncoder.scala
core/src/main/scala/stainless/verification/VerificationChecker.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/ScalaCompiler.scala

The only remaining warnings are those stemming from the `scalac` frontend, which uses general type projection due to the Scala 2 compiler relying on them.

Address warnings

---

core/src/main/scala/stainless/Component.scala
core/src/main/scala/stainless/MainHelpers.scala
core/src/main/scala/stainless/Report.scala
core/src/main/scala/stainless/extraction/package.scala
core/src/main/scala/stainless/extraction/trace/Trace.scala
core/src/main/scala/stainless/extraction/trace/Trees.scala
core/src/main/scala/stainless/utils/Serialization.scala
core/src/main/scala/stainless/verification/VerificationChecker.scala
frontends/library/stainless/annotation/annotations.scala

Improvements to equivalence checking phase, including: function call matching, conditional equivalence (--norm option), and user-provided test generators (mkTest annotation)

Improve equivalence checking

---

core/src/sphinx/faq.rst
core/src/sphinx/installation.rst

Can we merge this, @mario-bucev and then please also check if windows instructions need update to refer to dotty?
Nobody starting with stainless should probably use scala2 any more.

doc: Fixing dotty vs scalac and adding packaged library jar explanation

---

.larabot.conf

The larabot is apparently running these two removed tests under JDK8 while Stainless and its dependencies are compiled against JDK17

Temporarily remove failing tests

---

build.sbt
core/src/main/scala/stainless/Report.scala
core/src/main/scala/stainless/evaluators/EvaluatorReport.scala
core/src/main/scala/stainless/frontend/StainlessReports.scala
core/src/main/scala/stainless/genc/GenCComponent.scala
core/src/main/scala/stainless/termination/MeasureInference.scala
core/src/main/scala/stainless/termination/TerminationReport.scala
core/src/main/scala/stainless/verification/VerificationChecker.scala
core/src/main/scala/stainless/verification/VerificationComponent.scala
core/src/main/scala/stainless/verification/VerificationConditions.scala
core/src/main/scala/stainless/verification/VerificationReport.scala

* ~~Change measure inference timeout from n / 100 to n / 2 where n is the global verification timeout~~ 
Reverted, because it is not always appropriate (e.g. breaks `TerminationSuite`) 
* Some clean-up

Some clean-up and update Inox

---

bin/package-sbt-plugin.sh
build.sbt

This is necessary to have the `scalac` standalone work. Otherwise, it will not be able to read 3.2 Tasty file stemming from the Stainless library (which must not be removed).

Update `scalac` frontend to 2.13.10

---

core/src/main/scala/stainless/solvers/InoxEncoder.scala

In some circumstances (which I could not minimize sadly), this could lead to ill-formed SMT queries which for some reasons Z3 can handle but not CVC4.

Do not use description to name error variables

---

frontends/benchmarks/dotty-specific/valid/CaseObjectEnum1.scala
frontends/benchmarks/dotty-specific/valid/CaseObjectEnum2.scala
frontends/benchmarks/extraction/valid/CaseObject3.scala
frontends/benchmarks/extraction/valid/CaseObject4.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala

Add support for enum case objects when pattern matching, which used to trigger an error.

Support for enum case objects

---

frontends/benchmarks/verification/valid/RequireEnsuringMessages.scala
frontends/benchmarks/verification/valid/RequireEnsuringMessagesStaticChecks.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/ASTExtractors.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/FragmentChecker.scala
frontends/library/stainless/lang/StaticChecks.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/FragmentChecker.scala

Allows to write `require(p, "some message")` and `(...).ensuring(p, "another message")` for both the Scala and StaticChecks variants.

Support 'require' and 'ensuring' message overloads

---

core/src/main/scala/stainless/transformers/LatticesSimplifier.scala
core/src/main/scala/stainless/transformers/lattices/Core.scala
core/src/main/scala/stainless/transformers/lattices/Definitions.scala
core/src/main/scala/stainless/transformers/lattices/OL.scala
core/src/main/scala/stainless/verification/VerificationChecker.scala

- Add further simplification rules, such as `(if(b) T else E) == A` ~> `if(b) T == A else E == A` also for `<` `<=` etc (without duplicating `A` of course)
- Try to keep the memory consumption in-check

Some improvements to OL and OCBSL based simplifiers

---

core/src/main/scala/stainless/equivchk/EquivalenceChecker.scala
frontends/common/src/it/scala/stainless/equivchk/EquivChkSuite.scala

Before this PR, the strategy was to generate the maximum number of allowed matching (default of 16) and then perform pruning on it. Some picked matching may get pruned, leaving us with less than the limit which is not something we would like. 
This PR changes the behaviour to pick matching (passing the pruning test) as long as we don't go over the limit.

Equivalence checking: apply max limit on permutation while pruning

---

core/src/main/scala/stainless/Report.scala
core/src/main/scala/stainless/extraction/xlang/ConstructsUsage.scala
core/src/main/scala/stainless/extraction/xlang/package.scala

Closes #1366
For example, the following snippet:
```scala
import stainless.lang._
import stainless.collection._
import stainless.annotation._
object ExtractionSummary {
case class OuterClass(okField: Int, @extern externField: Int) {
def methodWithChoose: BigInt = choose((x: BigInt) => x >= 42)
def methodWithExternInner: BigInt = {
def inner: BigInt = {
@extern
def innerInnerInMethod: BigInt = 42
innerInnerInMethod
}
inner
}
}
def someFn(x: BigInt): BigInt = {
@extern
def innerExtern(x: BigInt) = x
def usingChoose: BigInt = choose((x: BigInt) => x >= 42)
x
}
def someFn2(x: BigInt, m: Map[BigInt, BigInt]): BigInt = {
@extern
def innerExtern2(x: BigInt) = x
def usingChoose2: BigInt = choose((x: BigInt) => x >= 42)
val z: BigInt = choose((x: BigInt) => x >= 42)
val useKeys = m.keys
x
}
def …
```

Report use of choose, `@extern` and `???` in the verification summary

---

core/src/main/scala/stainless/MainHelpers.scala
core/src/main/scala/stainless/equivchk/EquivalenceChecker.scala
core/src/main/scala/stainless/equivchk/EquivalenceCheckingComponent.scala
core/src/main/scala/stainless/frontend/package.scala

- Equivalence checking can now be used with `--watch` mode
- Model initial score can be overwritten with `--equivchk-init-weights=f1:w1,f2:w2,...`

Equivalence checking: add option to specify weights, output resulting weights & ctex in the JSON output, lift batch restriction

---

.larabot.conf
build.sbt
frontends/common/src/it/scala/stainless/ComponentTestSuite.scala
frontends/common/src/it/scala/stainless/verification/UncheckedSuite.scala
frontends/common/src/it/scala/stainless/verification/VerificationSuite.scala
frontends/dotty/src/it/scala/stainless/verification/DottyVerificationSuite.scala

cvc5 can be selected with `--solvers=smt-cvc5` (as long as its executable can be found in PATH).
The other changes relate to integration test: instead of loading `verification/` per solver, we do it only once.

Add support for smt-cvc5

---

frontends/dotty/src/main/scala/stainless/frontends/dotc/GhostAccessRewriter.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/GhostAccessRewriter.scala
sbt-plugin/src/sbt-test/sbt-plugin/ghost/test
sbt-plugin/src/sbt-test/sbt-plugin/simple/test

For the Scala 2 fronted, the `ghost` function used to generate invalid bytecode, so calls to this function are now explicitly removed. This problem does not apply to the Scala 3 frontend, but calls to `ghost` are also removed for symmetry.

Fix ghost rewriting phase

---

core/src/main/scala/stainless/verification/AssertionInjector.scala
frontends/benchmarks/imperative/invalid/NegativeArrayFill.scala

`Array.fill` requires a non-negative size

Add assertion for non-negative `Array.fill` size

---

frontends/benchmarks/extraction/invalid/NewArrayNonPrimitive.check
frontends/benchmarks/extraction/invalid/NewArrayNonPrimitive.scala
frontends/benchmarks/imperative/invalid/NewArrayNeg.scala
frontends/benchmarks/imperative/valid/NewArrayPrimitive.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala

This allows for efficient array creation (at runtime) for primitive types that are initialized to their zero value.

Support for `new Array(len)` constructor for primitive types

---

.larabot.conf

The Scala 2 frontend will still be tested on nightly.

Disable Scala 2 frontend when running CI for PRs

---

core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala
core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala
core/src/main/scala/stainless/extraction/imperative/TransformerWithType.scala
core/src/main/scala/stainless/extraction/imperative/Trees.scala
core/src/main/scala/stainless/extraction/termination/.scalafmt.conf
core/src/main/scala/stainless/genc/phases/Scala2IRPhase.scala
core/src/main/scala/stainless/utils/Serialization.scala
frontends/benchmarks/imperative/valid/CellSwap.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/ASTExtractors.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala
frontends/library/stainless/lang/Cell.scala
frontends/library/stainless/lang/package.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
libfiles.txt

Add a new `Cell` feature with a `swap` to support more mutability, notably swapping 2 variables.
This adds a new `Cell` class in the library, and a `swap` function exchanging their values:
```scala
case class Cell[@mutable T](var v: T) 
def swap[@mutable T](c1: Cell[T], c2: Cell[T]): Unit = {
val t = c2.v
c2.v = c1.v
c1.v = t
}
```
These can be used as follows:
```scala
import stainless.lang._
object Test {
def f(c1: Cell[Int], c2: Cell[Int]): Unit = {
require(c1.v == 1)
require(c2.v == 2)
c1.v = 3
swap(c1, c2)
assert(c1.v == 2)
assert(c2.v == 3)
}
}
```

Cell swap (#2)

---

core/src/main/scala/stainless/extraction/imperative/GhostChecker.scala
frontends/benchmarks/imperative/valid/WhileInvGhost.scala

This PR fixes `while` loops being treated as ghost when they referred to ghost constructs in their `invariant`.

Fix `while` loops being mistakenly considered as ghost

---

core/src/main/scala/stainless/extraction/imperative/ReturnElimination.scala
frontends/benchmarks/imperative/valid/RefnChecksWithReturn.scala

For instance, the provided tests in `RefnChecksWithReturn.scala` would unexpectedly generate "refinement checks for subtyping" which may result in being invalid due to #1463.

Applying some type widening in `ReturnElimination` to avoid triggering `AdtSpecialization`

---

core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala
core/src/main/scala/stainless/extraction/imperative/EffectsChecker.scala
frontends/benchmarks/extraction/invalid/AliasedFreshExpr.check
frontends/benchmarks/extraction/invalid/AliasedFreshExpr.scala
frontends/benchmarks/extraction/invalid/ArrayShenanigans1.check
frontends/benchmarks/extraction/invalid/ArrayShenanigans2.check
frontends/benchmarks/extraction/invalid/ArrayShenanigans3.check
frontends/benchmarks/extraction/invalid/ArrayShenanigans4.check
frontends/benchmarks/extraction/invalid/ArrayShenanigans5.check
frontends/benchmarks/extraction/invalid/BadAliasing1.check
frontends/benchmarks/extraction/invalid/BadAliasing2.check
frontends/benchmarks/extraction/invalid/IllegalAliasing.check
frontends/benchmarks/extraction/invalid/InnerClassesInvariants2.check
frontends/benchmarks/extraction/invalid/InnerClassesInvariants2.dotty.check
frontends/benchmarks/extraction/invalid/InnerClassesInvariants2.scala
frontends/benchmarks/extraction/invalid/InnerClassesInvariants2.scalac.check
frontends/benchmarks/extraction/invalid/MutateInside11.check
frontends/benchmarks/extraction/invalid/MutateInside12.check
frontends/benchmarks/extraction/invalid/RottenExpr1.check
frontends/benchmarks/extraction/invalid/RottenExpr1.scala
frontends/benchmarks/extraction/invalid/RottenExpr2.check
frontends/benchmarks/extraction/invalid/RottenExpr2.scala
frontends/benchmarks/extraction/invalid/RottenExpr3.dotty.check
frontends/benchmarks/extraction/invalid/RottenExpr3.scala
frontends/benchmarks/extraction/invalid/RottenExpr3.scalac.check
frontends/benchmarks/extraction/invalid/i1218.check
frontends/benchmarks/imperative/valid/FreshExpr.scala

Relax the condition over which an expression is considered to be "fresh" to include bindings of `match` expression and seeing through non-recursive function. 
It also changes the rule for `Let` for which I'm not so sure about:
Before: `Let(vd, e, b)` expression fresh iff `e` is fresh and *b* as well, where we consider `vd` as fresh when recurring on `b`
Now: `Let(vd, e, b)` fresh iff `b` is fresh, where we add `vd` as a fresh binding when recurring on `b` provided `e` is fresh.
These changes allows to accept [`FreshExpr.scala`](https://github.com/epfl-lara/stainless/blob/5ad0b33443a8c79671f30c84689d18d0cae25c5b/frontends/benchmarks/imperative/valid/FreshExpr.scala) (which was rejected before).
It also improves a bit the "illegal aliasing" error messages.

Relax `isExpressionFresh` and improve aliasing error messages

---

README.md
bin/launcher-cygwin-noscalaz3.tmpl.sh
bin/launcher-noscalaz3.tmpl.bat
bin/launcher-noscalaz3.tmpl.sh
bin/launcher.tmpl.sh
bin/package-standalone.sh
build.sbt
core/src/sphinx/gettingstarted.rst
core/src/sphinx/installation.rst
core/src/sphinx/options.rst
frontends/benchmarks/extraction/invalid/BadOverride2.scalac.check
frontends/benchmarks/extraction/invalid/BadOverride3.scalac.check
frontends/benchmarks/extraction/invalid/ExtendNonMutable.scalac.check
frontends/benchmarks/extraction/invalid/FieldInheritance2.scalac.check
frontends/benchmarks/extraction/invalid/ImpurePure1.scalac.check
frontends/benchmarks/extraction/invalid/ImpurePure2.scalac.check
frontends/benchmarks/extraction/invalid/InnerClassesInvariants2.check
frontends/benchmarks/extraction/invalid/MutableField.scalac.check
frontends/benchmarks/extraction/invalid/NonMutableTypeParameter.scalac.check
frontends/benchmarks/extraction/invalid/OpaqueInline.scalac.check
frontends/benchmarks/extraction/invalid/Purity1.scalac.check
frontends/benchmarks/extraction/invalid/Purity3.scalac.check
frontends/benchmarks/extraction/invalid/RottenExpr3.scalac.check
frontends/benchmarks/extraction/invalid/TraitVar1.scalac.check
frontends/benchmarks/extraction/invalid/i827b.scalac.check
frontends/common/src/it/scala/stainless/verification/FullImperativeSuite.scala
frontends/common/src/it/scala/stainless/verification/VerificationSuite.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/SimpleReporter.scala
stainless.conf.default

* Upgrade the Scala 2 frontend to 2.13.12
* Upgrade the shipped Z3 version (`smt-z3`) to 4.12.2
* Add cvc5 1.0.8 to the archive
* Add arm64 build for macOS
* Add the compiled and source code of the Stainless library to the archive, under `lib`
* Add a `stainless-cli` script to invoke `scala-cli` with the library.
* Rename `stainless.sh` to `stainless`

Prepare for the next release

---

frontends/benchmarks/extraction/invalid/GhostClass.dotty.check
frontends/benchmarks/extraction/invalid/GhostClass.scala
frontends/benchmarks/extraction/invalid/GhostClass.scalac.check
frontends/benchmarks/verification/valid/GhostClass.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/ASTExtractors.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala

PR #1472 changed the way propagation of annotation works, but I did not propagate `@ghost` annotation from `@ghost` class to methods. This PR fixes that.
Note that `@ghost` does not propagate to fields (see [here](https://github.com/epfl-lara/stainless/blob/106629548058cd72c31e965f05a415dc834d6abf/frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala#L500) where we explicitly ignore owners).

Propagate ghost annotation from class to methods

---

frontends/benchmarks/imperative/valid/i1306b.scala
frontends/benchmarks/imperative/valid/i1306c.scala
frontends/common/src/it/scala/stainless/termination/TerminationSuite.scala
frontends/common/src/it/scala/stainless/verification/ImperativeSuite.scala

`i1306b` is a nice test to ensure we do not regress on #1306 but it is sadly quite flaky.
I have disabled it (not deleted it) and have added a variant `i1306c` that does not make use of non-linear arithmetic (which seems to be the cause of the issue).

Disable test `i1306b`

---

core/src/main/scala/stainless/extraction/imperative/EffectsChecker.scala
core/src/sphinx/imperative.rst
frontends/benchmarks/extraction/invalid/ImpureInvariant.check
frontends/benchmarks/extraction/invalid/ImpureInvariant.scala
frontends/benchmarks/extraction/invalid/Purity3.dotty.check
frontends/benchmarks/extraction/invalid/Purity3.scalac.check
frontends/benchmarks/extraction/invalid/Purity4.dotty.check
frontends/benchmarks/extraction/invalid/Purity4.scala
frontends/benchmarks/extraction/invalid/Purity4.scalac.check
frontends/benchmarks/extraction/invalid/Purity5.dotty.check
frontends/benchmarks/extraction/invalid/Purity5.scala
frontends/benchmarks/extraction/invalid/Purity5.scalac.check
frontends/benchmarks/extraction/invalid/i1474.check
frontends/benchmarks/extraction/invalid/i1474.scala

Also adds some explanation when purity is expected, specifying which impure functions were called.
Closes #1474

Enforce purity for class invariants

---

core/src/main/scala/stainless/extraction/inlining/FunctionInlining.scala
frontends/benchmarks/verification/invalid/InvalidInvariantCopy.scala

In some cases, VCs positions could be incorrect when using inline functions.
This is particularly the case for synthetic `copy` methods which are always inlined.
For instance, in the following snippet, the VC generated for `mc.copy(x = y)` would incorrectly point at the definition of `MyClass`. This PR fixes this issue and the correct position is now reported.
```scala
case class MyClass(x: BigInt, y: BigInt)
def buildClass(mc: MyClass, x: BigInt): MyClass = {
mc.copy(x = y)
}.ensuring(_.x >= 0)
```

Fix positions for inlined functions

---

core/src/main/scala/stainless/equivchk/EquivalenceChecker.scala
core/src/main/scala/stainless/equivchk/EquivalenceCheckingComponent.scala
frontends/benchmarks/equivalence/separate/Candidate1.scala
frontends/benchmarks/equivalence/separate/Candidate2.scala
frontends/benchmarks/equivalence/separate/Model.scala
frontends/benchmarks/equivalence/separate/defs.scala
frontends/benchmarks/equivalence/separate/test_conf_1.json
frontends/benchmarks/equivalence/separate/test_conf_2.json

This PR allows having introducing `val` for tests, which may get created by some phases (e.g. the test in `separate/Model` contains binding introduced by `RefinementLifting`).
For unequivalence, it also outputs the expected result as well as the result from the candidate function.

Equivalence checker: allows for let-binding in tests and output 'expected but got' results

---

frontends/benchmarks/extraction/invalid/InvalidTypedPatterns1.dotty.check
frontends/benchmarks/extraction/invalid/InvalidTypedPatterns1.scala
frontends/benchmarks/extraction/invalid/InvalidTypedPatterns1.scalac.check
frontends/benchmarks/extraction/invalid/InvalidTypedPatterns2.dotty.check
frontends/benchmarks/extraction/invalid/InvalidTypedPatterns2.scala
frontends/benchmarks/extraction/invalid/InvalidTypedPatterns2.scalac.check
frontends/benchmarks/extraction/invalid/InvalidTypedPatterns3.dotty.check
frontends/benchmarks/extraction/invalid/InvalidTypedPatterns3.scala
frontends/benchmarks/extraction/invalid/InvalidTypedPatterns3.scalac.check
frontends/benchmarks/extraction/invalid/InvalidTypedPatterns4.dotty.check
frontends/benchmarks/extraction/invalid/InvalidTypedPatterns4.scala
frontends/benchmarks/extraction/invalid/InvalidTypedPatterns4.scalac.check
frontends/benchmarks/extraction/valid/StateMonadTypeRefIssue.scala
frontends/benchmarks/verification/valid/RedundantlyTypedPatterns.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala

Allows for ascribing type parameters to e.g. tuples patterns, such as in the following snippet:
```scala
def test[A, B, C](a: A, b: B, c: C): Unit = {
// annotating aa, bb and cc with their respecting type
val (aa: A, bb: B, cc: C) = (a, b, c)
}
```
This was previously rejected.
Note that the Scala 2 compiler will issue spurious warnings saying that these type tests cannot be checked at runtime (which is true, but they can be checked at compile time :yum:).

Allow for redundant type checks for pattern matching

---

core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala
frontends/benchmarks/imperative/valid/ArgsEffect1.scala
frontends/benchmarks/imperative/valid/ArgsEffect2.scala

`@pure` annotated functions were having their arguments exempt from effects analysis, which caused a crash on the two provided test cases.

Fix `EffectsAnalyzer` missing effects on arguments

---

core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala
frontends/benchmarks/imperative/valid/MutableArrayFieldInTrait.scala

`EffectsAnalyzer` crashes on the given file with the call `modify(mt.buf, j)` due to a missing case. This PR addresses that.

Fix `MatchError` in `EffectsAnalyzer`

---

core/src/main/scala/stainless/extraction/oo/RefinementLifting.scala
core/src/main/scala/stainless/extraction/oo/TypeOps.scala
frontends/benchmarks/verification/valid/ArrayOfTypeAlias.scala
frontends/benchmarks/verification/valid/PrivateIsFinal.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala
frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala

Small PR that addresses 3 minor issues:
-Add a missing case for arrays in `typeBounds`, which would otherwise cause `ArrayOfTypeAlias` to fail Stainless type-checking
-Annotate private methods with `xt.Final` since these cannot be overridden ("effectively final"). Now `PrivateIsFinal` passes
-Fix a small issue in `RefinementLifting` that would not properly update the type of each occurrence of variables whose type has been dealiased.

Add missing case for Array `typeBounds`, make private final, fix minor bug in `RefinementLifting`

---

core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala
core/src/main/scala/stainless/extraction/innerfuns/Definitions.scala
frontends/benchmarks/extraction/invalid/IllegalAliasing4.check
frontends/benchmarks/extraction/invalid/IllegalAliasing4.scala
frontends/benchmarks/extraction/invalid/Initialization1.scalac.check
frontends/benchmarks/extraction/invalid/Initialization2.scalac.check
frontends/benchmarks/extraction/invalid/Initialization3.scalac.check
frontends/benchmarks/extraction/invalid/Initialization4.scalac.check
frontends/benchmarks/extraction/invalid/Initialization5.scalac.check
frontends/benchmarks/extraction/invalid/MapAliasing1.check
frontends/benchmarks/extraction/invalid/MapAliasing2.check
frontends/benchmarks/extraction/invalid/i1099a.check
frontends/benchmarks/extraction/invalid/i1099c.check
frontends/benchmarks/extraction/invalid/i1099d.check
frontends/benchmarks/extraction/invalid/i1099d.scala
frontends/benchmarks/imperative/valid/TargetMutation3.scala
frontends/benchmarks/imperative/valid/TargetMutation4.scala
frontends/benchmarks/imperative/valid/TargetMutation5.scala
frontends/benchmarks/imperative/valid/TargetMutation6.scala
frontends/benchmarks/imperative/valid/TargetMutation7.scala
frontends/benchmarks/imperative/valid/TargetMutation8.scala
frontends/benchmarks/imperative/valid/TargetMutation9.scala

This relaxation allows the test cases of `TargetMutation{7,8}` to be accepted.
Note that the diff suggests a complete rewrite of the `Let` case but it is really just replacing `varsOfExprDealiased(e, env)` with `terminalVarsOfExprDealiased(e, env)`.

Relax fallback condition of `AntiAliasing` handling of `Let`

---

frontends/benchmarks/dotty-specific/valid/TypeAliasOpaque.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala

Apparently the oddity about opaque types as mentioned in the (deleted) comment is now gone, the special handling is no longer necessary (and would actually cause problem for aliases of opaque types).

Fix type alias of opaque triggering missing dependencies

---

core/src/main/scala/stainless/MainHelpers.scala

Before this change the information about the default value was duplicated in the docs of `--help`:
```txt
[  Info  ] --strict-arithmetic[=true|false]                 Check arithmetic operations for unintended behavior and overflows (default: true) (default: true)
```
The default value notice is added later, outside of the description string.

Remove duplicated default value doc

---

core/src/main/scala/stainless/equivchk/EquivalenceChecker.scala

Methods coming outside of the model and candidate functions do not benefit from pairwise matching, so this PR excludes them.

Equivalence checking: avoid pairwise matching of "external" methods

---

frontends/benchmarks/dotty-specific/invalid/ExportedMethods1.scala
frontends/benchmarks/dotty-specific/invalid/ExportedMethods2.scala
frontends/benchmarks/dotty-specific/invalid/ExportedMethods3.scala
frontends/benchmarks/dotty-specific/invalid/ExportedMethodsExt.scala
frontends/benchmarks/dotty-specific/valid/ExportedMethods.scala
frontends/benchmarks/dotty-specific/valid/ExportedMethodsExt.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/DottyCompiler.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/StainlessExtraction.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/StainlessPlugin.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/Utils.scala

The Scala compiler generates a forwarder for each exported method, however the preconditions are not taken into account, which means the forwarder will be invalid.
The idea is to drop these forwarded method and "de-alias" the symbol to get the original method or field.

Add support for exported methods

---

core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala
frontends/benchmarks/imperative/valid/ClassReconstruction.scala

Note that there was an already existing `@DropVCs` annotation that wrapped the expression, but in some instances the VC for class invariant was still being generated (even though it should not).
Note that removing the `final` makes verification pass, so this missing `@DropVCs` is certainly an oversight.
The `ClassReconstruction` sample showcases this.

Add missing `dropVCs` annotation in `AntiAliasing`

---

core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala
frontends/benchmarks/imperative/invalid/OpaqueMutation1.scala
frontends/benchmarks/imperative/invalid/OpaqueMutation2.scala
frontends/benchmarks/imperative/valid/ExternMutation.scala
frontends/benchmarks/imperative/valid/MutableTuple.scala
frontends/benchmarks/imperative/valid/OpaqueMutation1.scala
frontends/benchmarks/imperative/valid/OpaqueMutation2.scala
frontends/benchmarks/imperative/valid/PassByRef.scala
frontends/benchmarks/imperative/valid/TargetMutation10.scala
frontends/benchmarks/imperative/valid/TargetMutation4.scala
frontends/benchmarks/imperative/valid/TargetMutation6.scala
frontends/benchmarks/verification/false-valid/i1506.scala

`AntiAliasing#mapApplication` used to "rebuild" the mutated object(s) from function calls where a reassignment could be possible.
For instance, if we have:
```scala
case class Ref(var x: Int, var y: Int)
case class RefRef(var lhs: Ref, var rhs: Ref)
def modifyLhs(rr: RefRef, v: Int): Unit = {
rr.lhs.x = v
rr.lhs.y = v
}
def test(testRR: RefRef): Unit = {
val rrAlias = testRR
val lhsAlias = testRR.lhs
modifyLhs(testRR, 123)
// ...
}
```
Then before this PR, `mapApplication` would transform `test` as follows:
```scala
def modifyLhs(rr: RefRef, v: Int): (Unit, RefRef) = 
((), RefRef(Ref(v, v), rr.rhs))
def test(testRR: RefRef) = {
var rrAlias: RefRef = testRR
var lhsAlias: Ref = testRR.lhs
val res: (Unit, RefRef) = modifyLhs(testRR, 123)
testRR = RefRef(Ref(res._2.lhs.x, testRR.lhs.y), …
```

AntiAliasing: avoid rebuilding mutated objects when possible

---

core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala
frontends/benchmarks/imperative/valid/FreshExpr1.scala
frontends/benchmarks/imperative/valid/FreshExpr2.scala

It seems that when recurring on the body of the (non-recursive) function, the intent was to use `rec` with `bindings` and not the top-level `isExpressionFresh` function?

Have isExpressionFresh consider arguments when computing freshness of a function call

---

bin/package-standalone.sh
build.sbt
core/src/main/scala/stainless/Report.scala
core/src/main/scala/stainless/equivchk/EquivalenceChecker.scala
core/src/main/scala/stainless/equivchk/EquivalenceCheckingComponent.scala
core/src/main/scala/stainless/equivchk/EquivalenceCheckingReport.scala
core/src/main/scala/stainless/evaluators/EvaluatorReport.scala
core/src/main/scala/stainless/genc/GenCComponent.scala
core/src/main/scala/stainless/termination/TerminationReport.scala
core/src/main/scala/stainless/testgen/GenCTestGen.scala
core/src/main/scala/stainless/testgen/ScalaTestGen.scala
core/src/main/scala/stainless/verification/CoqVerificationChecher.scala
core/src/main/scala/stainless/verification/VerificationAnalysis.scala
core/src/main/scala/stainless/verification/VerificationCache.scala
core/src/main/scala/stainless/verification/VerificationChecker.scala
core/src/main/scala/stainless/verification/VerificationComponent.scala
core/src/main/scala/stainless/verification/VerificationConditions.scala
core/src/main/scala/stainless/verification/VerificationReport.scala

Should be merged after #1507 
and with the Inox modification https://github.com/epfl-lara/inox/pull/206

Add the SMT lib file ID in the report table if the option `debug=smt` is enabled

---

.larabot.conf
core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala

PR #1507 made some changes to `mapApplication`, and one I made by negligence (in the diff line) turned out to unveil an issue in the `Let` case handling of `AntiAliasing` ([line in question](https://github.com/epfl-lara/stainless/blob/c4b33d13d21c3bf5657d32d498e788b4783bfe5c/core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala#L675)).
Here, we compute the targets of the *transformed* binding. If this binding happens to contain a function call, the returned targets may be invalid because `getTargets` works on functions prior to the `AntiAliasing` function purification, not after (as it's done here).
The reason this issue did not arise before is the `var` introduced by `mapApplication` prevented target computation, which ultimately resulted in …

AntiAliasing: restore var binding in mapApplication

---

build.sbt
frontends/benchmarks/extraction/invalid/Initialization5.dotty.check
frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala

- FunctionOf tree changed
- Use Iterable instead of Traversable

Scala version bump to 3.3.3

---

core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala
core/src/main/scala/stainless/extraction/inlining/UnfoldOpaque.scala
core/src/main/scala/stainless/extraction/package.scala
frontends/benchmarks/imperative/valid/UnfoldOpaqueMutate.scala
frontends/benchmarks/verification/valid/UnfoldOpaqueVal.scala

Previously, performing an `unfold` on a `val` to a function or on an imperative function would do nothing.

Enhance unfold to work on bindings and imperative code as well

---

frontends/library/stainless/collection/List.scala
frontends/library/stainless/collection/ListSpecs.scala

Add more specs to List functions using bitvector indexing

---

bin/launcher-noscalaz3.tmpl.bat

The current release fails when invoked from paths that contain spaces, because the current path was not escaped. This PR adds quotes around the current path

Quote paths correctly to fix problems with paths containing spaces

---

frontends/benchmarks/equivalence/adjlist/AdjList.scala
frontends/benchmarks/equivalence/adjlist/test_conf.json
frontends/benchmarks/equivalence/arrayContent/ArrayContent.scala
frontends/benchmarks/equivalence/arrayContent/test_conf.json
frontends/benchmarks/equivalence/arrayHeap/ArrayHeap.scala
frontends/benchmarks/equivalence/arrayHeap/test_conf.json
frontends/benchmarks/equivalence/arrayIncreasing/ArrayIncreasing.scala
frontends/benchmarks/equivalence/arrayIncreasing/test_conf.json
frontends/benchmarks/equivalence/finiteStreams/FiniteStreams.scala
frontends/benchmarks/equivalence/finiteStreams/test_conf.json
frontends/benchmarks/equivalence/maxHeapify/MaxHeapify.scala
frontends/benchmarks/equivalence/maxHeapify/test_conf.json
frontends/benchmarks/equivalence/partial/Partial.scala
frontends/benchmarks/equivalence/partial/test_conf.json
frontends/benchmarks/equivalence/sortedArray/SortedArray.scala
frontends/benchmarks/equivalence/sortedArray/test_conf.json
frontends/benchmarks/equivalence/valid2DLength/Valid2DLength.scala
frontends/benchmarks/equivalence/valid2DLength/test_conf.json

Adding benchmarks from our iFM'24 short paper: Proving Termination via Measure Transfer in Equivalence Checking.

Add iFM24 benchmarks

---

build.sbt
core/src/main/scala/stainless/MainHelpers.scala
core/src/main/scala/stainless/frontend/package.scala
core/src/main/scala/stainless/verification/VerificationConditions.scala
frontends/common/src/it/scala/stainless/LibrarySuite.scala
frontends/common/src/test/scala/stainless/InputUtils.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/DottyCompiler.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/StainlessExtraction.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/SymbolMapping.scala

This PR enables loading trees from Tasty files located on the class path. This feature:
1. can be used via the newly introduced `--classpath` option,
2. and is enabled by default to load the Stainless standard library.
- Loading trees from Tasty is handled transparently by Dotty. We call `.rootTree` on the unit’s class symbol, which works because the `-Yretain-trees` compiler option instructs Dotty to keep Tasty trees.
- Extracting these trees is done in `StainlessExtraction.extractTastyUnits`. This method is invoked from `DottyCompiler.runOn`, which runs after all source compilation units have been processed.
- The set of Tasty unit trees to extract is computed as follows:
- A base set of “used Tasty units” is stored in `SymbolMapping`. It can be retrieved with …

Add support for extracting from Tasty

---

core/src/main/scala/stainless/frontend/BatchedCallBack.scala
core/src/main/scala/stainless/frontend/CallBack.scala
core/src/main/scala/stainless/frontend/SplitCallBack.scala
frontends/common/src/test/scala/stainless/InputUtils.scala

`Callback.failed` is always a no-op, and is not called from anywhere. This PR removes it.

Remove Callback.failed

---

core/src/main/scala/stainless/ast/Deconstructors.scala
core/src/main/scala/stainless/ast/ExprOps.scala
core/src/main/scala/stainless/ast/Expressions.scala
core/src/main/scala/stainless/ast/Printers.scala
core/src/main/scala/stainless/ast/SymbolOps.scala
core/src/main/scala/stainless/ast/TypeOps.scala
core/src/main/scala/stainless/evaluators/RecursiveEvaluator.scala
core/src/main/scala/stainless/extraction/oo/TransformerWithType.scala
core/src/main/scala/stainless/extraction/oo/TypeEncoding.scala
core/src/main/scala/stainless/extraction/oo/TypeOps.scala
core/src/main/scala/stainless/genc/phases/Scala2IRPhase.scala
core/src/main/scala/stainless/transformers/lattices/Core.scala
core/src/main/scala/stainless/transformers/lattices/Definitions.scala
core/src/main/scala/stainless/utils/Serialization.scala
core/src/main/scala/stainless/verification/CoqEncoder.scala
frontends/benchmarks/extraction/valid/PatternAlternative1 copy.scala
frontends/benchmarks/extraction/valid/PatternAlternative2.scala
frontends/benchmarks/verification/valid/PatternAlternative.scala
frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala

Addresses issues #1128 and #617 by adding support for pattern alternatives in Stainless. 
This was done in the context of our project in the Formal Verification CS-550 course. This version adds a new Alternative pattern and handles it throughout the pipeline and therefore allows disjunctions of patterns to be used.
Note: This does not yet add support for pattern alternatives in the Coq encoder or GenC, but does include support for pattern alternatives when using the optional simplifiers OL and OCBSL.

Add support for pattern alternatives

---

README.md

Adds the following section to the README, describing the AUR package, copied to be rendered here:
==========================================================
A package for Stainless is available on the Arch User Repository (AUR) for ArchLinux as [`stainless-git`](https://aur.archlinux.org/packages/stainless-git), which follows the latest commit on the `main` branch. You can use your favorite AUR helper (we've tried `yay`, see [AUR Helpers](https://wiki.archlinux.org/title/AUR_helpers)),  or follow the [detailed instructions as on the ArchWiki](https://wiki.archlinux.org/title/Arch_User_Repository#Installing_and_upgrading_packages) to install the package.
For quick reference, with `yay` (or other AUR helpers accordingly):
```shell
yay -S stainless-git
```
and manually:
```shell
git clone …
```

Add AUR package reference and instructions

---

README.md
snap/local/stainless
snap/local/stainless-cli
snap/snapcraft.yaml

Adds the folder `snap/` containing a snap build file and two scripts to launch `stainless` and `stainless.cli` in the appropriate container environment.
The build is more manual scripting than one would like, but Snap has no Scala/sbt plugin/build, only Maven/Gradle. 
Once the build files are merged, we can also try and set up automatic builds to the Snap store when we commit to main. 
The following section is inserted into the README right above the AUR install instructions:
=========================================================================
A package for Stainless is available on the Snap store as [`stainless`](https://snapcraft.io/stainless) with an experimental edge release. It can be used to install and run Stainless on any Snap enabled system (e.g. Ubuntu).
In a terminal, you …

Add a Snapcraft Build and Snap Install Instructions

---

README.md
build.sbt
core/src/main/scala/stainless/codegen/CodeGeneration.scala

- update readme with more explicit use instructions, clarify things where needed
- update cafebabe to a Scala 3 version 
- update Inox due to recent scala-smtlib fix
With this dependency update, Stainless works on JDK 21 for me.
The installation instructions have not yet been split from the readme.

Update readme and dependencies
