epfl-lara/stainless

LICENSE, build.sbt, src/main/scala/stainless/Main.scala, src/main/scala/stainless/extraction/inlining/FunctionInlining.scala
Prints help string with --help option.
For now, options are not separated into categories so the output is pretty ugly, but it's functional.
Solves https://github.com/epfl-lara/stainless/issues/1
=> Basic help message printing

build.sbt, core/src/main/scala/stainless/MainHelpers.scala, core/src/main/scala/stainless/codegen/CodeGeneration.scala, core/src/main/scala/stainless/extraction/PreconditionInference.scala, core/src/main/scala/stainless/termination/ProcessingPipeline.scala, core/src/main/scala/stainless/termination/Strengthener.scala, core/src/main/scala/stainless/termination/TerminationChecker.scala, core/src/main/scala/stainless/verification/VerificationChecker.scala, core/src/main/scala/stainless/verification/VerificationConditions.scala, frontends/scalac/src/it/scala/stainless/ComponentTestSuite.scala, frontends/scalac/src/it/scala/stainless/termination/TerminationSuite.scala, frontends/scalac/src/it/scala/stainless/verification/VerificationSuite.scala
Mostly copied from https://github.com/epfl-lara/leon/pull/297
=> Solver unsupported

README.md
Addresses https://github.com/epfl-lara/stainless/issues/8
=> Point to Inox + Leon in README

core/src/main/scala/stainless/termination/DecreasesProcessor.scala, core/src/main/scala/stainless/termination/Trees.scala, frontends/library/stainless/math/package.scala, testcases/termination/usermeasure/Ackermann.scala, testcases/termination/usermeasure/BinomialHeap.scala, testcases/termination/usermeasure/McCarthy91.scala, testcases/termination/usermeasure/MergeSortTermination.scala, testcases/termination/usermeasure/OddEvenComplex.scala, testcases/termination/usermeasure/OddEvenMoreComplex.scala, testcases/termination/usermeasure/OddEvenSimple.scala
=> Fixing minor bugs in termination checking using decreases and adding some testcases

frontends/dotty/src/main/scala/stainless/frontends/dotc/ASTExtractors.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
=> Extract scala.Predef.identity

frontends/benchmarks/extraction/Extraction4.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
See new regression test for details. Dotty frontend was not concerned by this bug.
=> Patch for trait extraction

frontends/benchmarks/verification/invalid/StaticChecks2.scala, frontends/benchmarks/verification/invalid/StaticChecks3.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/ASTExtractors.scala, frontends/library/stainless/lang/StaticChecks.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala
See https://github.com/epfl-lara/stainless/commit/142e0e663d8184a84876fdbaa3025ea6b0b59ab6#commitcomment-25072830
=> Import missing static checks from Leon's library

core/src/sphinx/purescala.rst, frontends/library/stainless/lang/package.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala
Related to #135.
I've noticed some additional dead pieces of code. Commits can be reverted if/when adding support the those features.
=> Cleanup: remove dead code and unsupported features from the library

core/src/main/scala/stainless/MainHelpers.scala, core/src/main/scala/stainless/Report.scala, core/src/main/scala/stainless/package.scala, core/src/sphinx/options.rst
=> Add explicit --compact option

core/src/main/scala/stainless/termination/DatatypeChecker.scala, core/src/main/scala/stainless/termination/ProcessingPipeline.scala, core/src/main/scala/stainless/termination/TerminationAnalysis.scala, core/src/main/scala/stainless/termination/TerminationChecker.scala, frontends/benchmarks/termination/looping/NegativeDatatype.scala, frontends/benchmarks/verification/invalid/Choose1.scala
Fixes https://github.com/epfl-lara/stainless/issues/120
=> Reject negative datatypes in termination checker

RELEASE_README.md, build.sbt, project/plugins.sbt, sbt-plugin/src/main/scala/ch/epfl/lara/sbt/stainless/StainlessPlugin.scala, sbt-plugin/src/sbt-test/sbt-plugin/simple/project/TestPlugin.scala, version.sbt
Evidence that publishing works can be found here: https://bintray.com/epfl-lara
I'll open a new PR for documenting how to use the sbt-stainless plugin.
=> Publish all modules to bintray. Re #157

frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/FragmentChecker.scala
This PR is the next step after #177 is merged. It removes some checks performed during code extraction and moves them to the fragment checker.
=> Simplify extraction

core/src/sphinx/gettingstarted.rst
=> Rework 'Getting started' page a bit

core/src/main/scala/stainless/solvers/InoxEncoder.scala
=> Remove flags on both functions and sorts

core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala, core/src/main/scala/stainless/extraction/imperative/EffectsChecker.scala, core/src/main/scala/stainless/extraction/inlining/FunctionInlining.scala, core/src/main/scala/stainless/extraction/oo/AdtSpecialization.scala, core/src/main/scala/stainless/frontend/StainlessCallBack.scala, core/src/main/scala/stainless/utils/Serialization.scala, core/src/main/scala/stainless/verification/DefaultTactic.scala, core/src/main/scala/stainless/verification/VerificationChecker.scala, core/src/main/scala/stainless/verification/VerificationConditions.scala, frontends/benchmarks/extraction/invalid/CopyMut.scala, frontends/benchmarks/extraction/valid/Copy.scala, frontends/benchmarks/extraction/valid/DefaultParam.scala, frontends/benchmarks/verification/invalid/CopyInv.scala, frontends/benchmarks/verification/valid/Copy.scala, frontends/benchmarks/verification/valid/CopyInv.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/ASTExtractors.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
=> Add support for 'copy' method and default parameters

build.sbt, core/src/main/scala/stainless/extraction/imperative/ImperativeCodeElimination.scala, core/src/main/scala/stainless/extraction/xlang/TreeSanitizer.scala, core/src/main/scala/stainless/termination/Trees.scala
We need still to discuss how to prove the well-foundedness of the annotated measure whether it is responsability of the user or the system.
=> Allowing decreases annotations in while loops

core/src/main/scala/stainless/extraction/imperative/ImperativeCodeElimination.scala
Instead of doing the translation:
def f() = ... while(c) b ...
def f() = ... fwhile() ...                        
def fwhile() = if(c){ fwhile() } 
I do the translation:
def f() = ... if(c) fwhile()     
def fwhile() = require(c) b if(c) fwhile() 
with this translation in the example:
while (x > 0) {
decreases(x)
x = x - 1
}
one can use decreases(x) instead of decreases(max(x,0))
=> Transforming while to do-while to use loop-condition as precondition

core/src/main/scala/stainless/utils/Serialization.scala
Should I set `Synthetic` to 149?
=> Fix serialization of Private/Ghost (both 147)

core/src/main/scala/stainless/ast/SymbolIdentifier.scala, core/src/main/scala/stainless/extraction/methods/DependencyGraph.scala, core/src/main/scala/stainless/extraction/methods/Laws.scala, core/src/main/scala/stainless/extraction/methods/MethodLifting.scala, core/src/main/scala/stainless/extraction/oo/DependencyGraph.scala, core/src/main/scala/stainless/verification/DefaultTactic.scala, frontends/benchmarks/verification/invalid/DisrespectfulOverride.scala, frontends/benchmarks/verification/invalid/DisrespectfulOverride2.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala
Add dependency from override to overridden method, and Derived flags (to overrides) in synthesized methods (`MethodLifting`)
=> Add dependency from override to overridden method

core/src/main/scala/stainless/verification/VerificationCache.scala, core/src/main/scala/stainless/verification/VerificationChecker.scala
Does `simplifyExpr` subsume `simplifyLets`?
=> Simplify verification conditions before caching and displaying

build.sbt, core/src/main/scala/stainless/extraction/methods/FieldAccessors.scala, core/src/main/scala/stainless/extraction/methods/MethodLifting.scala, core/src/main/scala/stainless/extraction/methods/Sealing.scala, core/src/main/scala/stainless/extraction/oo/AdtSpecialization.scala, core/src/main/scala/stainless/extraction/oo/Definitions.scala, core/src/main/scala/stainless/extraction/utils/PositionChecker.scala, frontends/benchmarks/extraction/valid/AccessorFlags.scala, frontends/stainless-dotty/src/it/scala/stainless/DottyExtractionSuite.scala
Fix the missing position in https://github.com/epfl-lara/stainless/issues/386
=> Add missing positions in Sealing and FieldAccessors

build.sbt, core/src/main/scala/stainless/ast/Definitions.scala, core/src/main/scala/stainless/ast/ExprOps.scala, core/src/main/scala/stainless/codegen/CodeGeneration.scala, core/src/main/scala/stainless/codegen/CompilationUnit.scala, core/src/main/scala/stainless/extraction/inlining/FunctionInlining.scala, core/src/main/scala/stainless/extraction/oo/Definitions.scala, core/src/main/scala/stainless/termination/ControlFlowAnalysis.scala, core/src/main/scala/stainless/termination/StructuralSize.scala, core/src/main/scala/stainless/termination/Trees.scala, core/src/main/scala/stainless/utils/Canonization.scala, core/src/main/scala/stainless/utils/IncrementalComputationalGraph.scala, core/src/main/scala/stainless/utils/Registry.scala, core/src/main/scala/stainless/verification/VerificationCache.scala, core/src/main/scala/stainless/verification/VerificationChecker.scala, frontends/common/src/test/scala/stainless/RegistryTestSuite.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/ASTExtractors.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/SymbolsContext.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/ScalaCompiler.scala, sbt-plugin/src/sbt-test/sbt-plugin/simple/build.sbt
(For compatibility with https://marketplace.visualstudio.com/items?itemName=scalameta.metals)
=> Bumping scalac to version 2.11.12

core/src/main/scala/stainless/package.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
=> Fix for line numbers sometimes being off

build.sbt, core/src/main/scala/stainless/Component.scala, core/src/main/scala/stainless/MainHelpers.scala, core/src/main/scala/stainless/frontend/StainlessCallBack.scala, core/src/main/scala/stainless/transformers/SimplifierWithSolver.scala, core/src/main/scala/stainless/utils/FileWatcher.scala, frontends/benchmarks/extraction/valid/LazyVal.scala, frontends/benchmarks/termination/valid/PackratParsing.scala, frontends/benchmarks/termination/valid/Viterbi.scala, frontends/scalac/src/it/scala/stainless/ScalacExtractionSuite.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala, sbt-plugin/src/sbt-test/sbt-plugin/ghost/project/build.properties, sbt-plugin/src/sbt-test/sbt-plugin/ghost/test, sbt-plugin/src/sbt-test/sbt-plugin/simple/build.sbt, sbt-plugin/src/sbt-test/sbt-plugin/simple/test
=> Bump Scala to v2.12.8

frontends/benchmarks/extraction/valid/ImportStatements.scala, frontends/benchmarks/extraction/valid/TupleSelect.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala, frontends/stainless-dotty/src/main/scala/stainless/frontends/dotc/StainlessExtraction.scala
=> Allow fields/methods named after tuple selectors

core/src/main/scala/stainless/transformers/SimplifierWithPC.scala, core/src/main/scala/stainless/utils/Registry.scala, core/src/main/scala/stainless/verification/VerificationChecker.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/ASTExtractors.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala
Fixes https://github.com/epfl-lara/stainless/issues/406
=> Remove all assertions, and use assumeChecked for simplifications

core/src/main/scala/stainless/frontend/StainlessReports.scala
=> Ensure report table has the same number of columns for every component

core/src/main/scala/stainless/extraction/oo/RefinementLifting.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala
- ADTs
- Enumerations
- Intersection Types
- Union Types
- Type Lambdas
- Match Types
- Typeclass Derivation
- Multiversal Equality
- Trait Parameters
- Inlining by Rewriting
- Meta Programming
- By-Name Implicits
- Auto Parameter Tupling
- Named Type Arguments
- Witnesses
- Top-level definitions
- Kind Polymorphism
- TASTy Reflect
=> Upgrade Dotty to 0.12.0-RC1

core/src/sphinx/casestudies.rst, core/src/sphinx/conf.py, core/src/sphinx/ghost.rst, core/src/sphinx/imperative.rst, core/src/sphinx/index.rst, core/src/sphinx/intro.rst, core/src/sphinx/laws.rst, core/src/sphinx/library.rst, core/src/sphinx/neon.rst, core/src/sphinx/purescala.rst, core/src/sphinx/verification.rst, core/src/sphinx/wrap.rst, frontends/benchmarks/extraction/valid/ExternFallback1.scala, frontends/benchmarks/verification/invalid/ExternFallbackMut.scala, frontends/benchmarks/verification/valid/Actors.scala, frontends/benchmarks/verification/valid/ArraySlice.scala, frontends/benchmarks/verification/valid/ExternField.scala, frontends/benchmarks/verification/valid/ExternFieldPure.scala, frontends/benchmarks/verification/valid/MsgQueue.scala, frontends/library/stainless/annotation/annotations.scala, frontends/library/stainless/collection/CMap.scala, frontends/library/stainless/lang/Option.scala, frontends/scalac/src/it/scala/stainless/verification/VerificationSuite.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/FragmentChecker.scala, sbt-plugin/src/sbt-test/sbt-plugin/ghost/actor-tests/src/main/scala/Actors.scala
=> Document latest features

frontends/library/stainless/lang/package.scala
=> Remove inline annotation on stainless.lang.ghost

core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala
I noticed the code is not as the case for array update which is above (my bad), this PR should fix it.
=> Fix check in mutable map effect analysis

frontends/benchmarks/verification/valid/InnerClasses5.scala
=> Re-enable benchmark disabled in 8398729d6 and fixed in 6f0a020

RELEASE_NOTES.md, build.sbt, core/src/main/scala/stainless/MainHelpers.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/ScalaCompiler.scala, project/plugins.sbt
=> Add `--version` flag

build.sbt, core/src/main/scala/stainless/MainHelpers.scala, core/src/main/scala/stainless/frontend/BatchedCallBack.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/ScalaCompiler.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/StainlessExtraction.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/StainlessPlugin.scala, sbt-plugin/src/main/scala/ch/epfl/lara/sbt/stainless/StainlessPlugin.scala, sbt-plugin/src/sbt-test/sbt-plugin/ghost/actor-tests/src/main/scala/Actors.scala, sbt-plugin/src/sbt-test/sbt-plugin/ghost/actor-tests/src/main/scala/Counter.scala, sbt-plugin/src/sbt-test/sbt-plugin/ghost/basic/TestGhost1.scala, sbt-plugin/src/sbt-test/sbt-plugin/ghost/build.sbt
=> Fix sbt plugin, metals integration, and tests

build.sbt, core/src/sphinx/installation.rst, sbt-plugin/src/main/scala/ch/epfl/lara/sbt/stainless/StainlessPlugin.scala
=> Update sbt docs and fix plugin publishing issues

frontends/scalac/src/main/scala/stainless/frontends/scalac/StainlessExtraction.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/StainlessPlugin.scala
=> Fix report being shown twice

frontends/benchmarks/typechecker/valid/AbstractPost.scala, frontends/benchmarks/typechecker/valid/ExternPost.scala, frontends/benchmarks/typechecker/valid/IndexOfInjective.scala, frontends/benchmarks/typechecker/valid/PostConditionInTuple.scala, frontends/benchmarks/verification/invalid/PreInPre.scala
I've added them to the type-checker folder since they also go through with the type-checker option.
=> Microtests from recently closed issues

core/src/main/scala/stainless/extraction/methods/FieldAccessors.scala, core/src/main/scala/stainless/extraction/methods/Trees.scala, core/src/main/scala/stainless/frontend/BatchedCallBack.scala, core/src/main/scala/stainless/frontend/SplitCallBack.scala, frontends/benchmarks/extraction/invalid/MissingAbstractOverride.scala, frontends/benchmarks/verification/valid/Havoc.scala, frontends/common/src/test/scala/stainless/InputUtils.scala
=> Re-enable check for abstract methods overrides and consider methods of abstract classes with empty body to be abstract

frontends/benchmarks/verification/valid/LastDynAssert.scala
=> Add benchmark for #532

core/src/main/scala/stainless/extraction/oo/Trees.scala, frontends/benchmarks/extraction/valid/TypeMembers5.scala
=>  Dealias type aliases more eagerly

.gitignore, RELEASE_NOTES.md, build.sbt, core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala, core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala, core/src/main/scala/stainless/extraction/imperative/SymbolOps.scala, core/src/main/scala/stainless/extraction/methods/Laws.scala, core/src/main/scala/stainless/extraction/methods/MethodLifting.scala, core/src/main/scala/stainless/extraction/methods/MutabilityAnalyzer.scala, core/src/main/scala/stainless/extraction/methods/Sealing.scala, core/src/main/scala/stainless/extraction/methods/Trees.scala, core/src/main/scala/stainless/extraction/methods/TypeOps.scala, core/src/main/scala/stainless/extraction/methods/package.scala, core/src/main/scala/stainless/extraction/oo/AdtSpecialization.scala, core/src/main/scala/stainless/extraction/oo/Definitions.scala, core/src/main/scala/stainless/extraction/oo/RefinementLifting.scala, core/src/main/scala/stainless/extraction/oo/TransformerWithType.scala, core/src/main/scala/stainless/extraction/oo/Trees.scala, core/src/main/scala/stainless/extraction/oo/TypeEncoding.scala, core/src/main/scala/stainless/extraction/oo/TypeOps.scala, core/src/main/scala/stainless/extraction/xlang/TreeSanitizer.scala, core/src/main/scala/stainless/extraction/xlang/package.scala, core/src/main/scala/stainless/frontend/BatchedCallBack.scala, core/src/main/scala/stainless/frontend/SplitCallBack.scala, frontends/benchmarks/extraction/valid/CaseObjectTypeMember.scala, frontends/benchmarks/extraction/valid/TypeMembers0.scala, frontends/benchmarks/verification/valid/StateMachine.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala
=> Fix issues with type members

bin/package-standalone.sh
Just a quick check that the required tools are installed on the machine before running the packaging, to avoid being surprised with errors (as I was since I did not have zip installed :-) ).
=> Quick check that tools are installed before packaging

bin/package-standalone.sh
This will print a warning when the issue in https://github.com/epfl-lara/smart/issues/12 arises.
=> Add readability check for jars in script

.larabot.conf
Let's see if this improves the test suite reliability when having concurrent builds.
=> Decrease parallelism in tests

core/src/main/scala/stainless/extraction/oo/AdtSpecialization.scala, frontends/benchmarks/extraction/valid/MethodInCaseObject.scala
=> Fix malformed case object constructor method

frontends/benchmarks/dotty-specific/valid/IdentityRefinement.scala
=> Add benchmark for #535

frontends/benchmarks/extraction/valid/NonGhostUpdate.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/FragmentChecker.scala
=>  Propagate @ghost annotation to variables introduced by calls to default copy getter

.larabot.conf, bin/bolts-tests.sh, bin/external-tests.sh, bin/stainless-actors-tests.sh
This is a script we discussed with @romac that can be used to run more extensive tests on external benchmarks (bolts, stainless-actors).
=> Add script to run tests on stainless-actors and bolts

core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala, core/src/main/scala/stainless/extraction/imperative/EffectsChecker.scala, frontends/benchmarks/extraction/valid/MapAliasing.scala
=> Conditional effect targets for non-recursive functions

frontends/benchmarks/verification/valid/BVMaxInterpret.scala
Inspired from https://tube.switch.ch/videos/166c6218
=> Add new bvmax interpreter benchmark

frontends/benchmarks/typechecker/valid/GodelNumbering.scala
Fix https://github.com/epfl-lara/stainless/issues/677
=> Fix bad mutual recursion in GodelNumbering proof

frontends/benchmarks/verification/valid/ContMonad.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
Also ignores AnyVal as a class parent during extraction.
=> Add Cont monad benchmark with exceptions

core/src/sphinx/purescala.rst
=> Document type aliases and type members

build.sbt, core/src/sphinx/installation.rst, project/build.properties, sbt-plugin/project/build.properties, sbt-plugin/src/main/scala/ch/epfl/lara/sbt/stainless/StainlessPlugin.scala, sbt-plugin/src/sbt-test/sbt-plugin/ghost/project/build.properties
=> Update sbt to 1.3.0

frontends/benchmarks/verification/valid/MyMap.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala, frontends/library/stainless/lang/Map.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
=> Add support for removing elements from Map

core/src/main/scala/stainless/ast/Deconstructors.scala, core/src/main/scala/stainless/ast/ExprOps.scala, core/src/main/scala/stainless/ast/TypeOps.scala, core/src/main/scala/stainless/extraction/imperative/ImperativeCodeElimination.scala, core/src/main/scala/stainless/extraction/methods/Sealing.scala
Blocked by https://github.com/epfl-lara/inox/pull/107
=> Fix some missing and wrong positions

frontends/benchmarks/extraction/invalid/InnerClass.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/FragmentChecker.scala
=> Disallow defining classes within a class body

core/src/main/scala/stainless/ast/Deconstructors.scala, core/src/main/scala/stainless/ast/Definitions.scala, core/src/main/scala/stainless/solvers/InoxEncoder.scala, core/src/main/scala/stainless/utils/Serialization.scala, core/src/main/scala/stainless/verification/AssertionInjector.scala, core/src/main/scala/stainless/verification/VerificationComponent.scala, core/src/sphinx/tutorial.rst, frontends/benchmarks/strictarithmetic/invalid/Wrapping1.scala, frontends/benchmarks/strictarithmetic/invalid/Wrapping2.scala, frontends/benchmarks/strictarithmetic/valid/Wrapping1.scala, frontends/benchmarks/strictarithmetic/valid/Wrapping2.scala, frontends/common/src/it/scala/stainless/verification/ComponentTestSuite.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/ASTExtractors.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala, frontends/library/stainless/annotation/annotations.scala, frontends/library/stainless/math/package.scala, frontends/scalac/src/it/scala/stainless/verification/StrictArithmeticSuite.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
=> Enable strict arithmetic by default

core/src/main/scala/stainless/extraction/methods/FieldAccessors.scala, core/src/main/scala/stainless/extraction/methods/Trees.scala, core/src/main/scala/stainless/extraction/methods/ValueClasses.scala, core/src/main/scala/stainless/extraction/methods/package.scala, core/src/main/scala/stainless/extraction/package.scala, core/src/main/scala/stainless/utils/Serialization.scala, frontends/benchmarks/verification/valid/ValueClasses.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
=> Erase value classes

frontends/library/stainless/io/StdOut.scala
Fix https://github.com/epfl-lara/stainless/issues/759
=> Change StdOut print functions to handle Any

project/build.properties
=> Revert "Update sbt version"

.larabot.conf, README.md, bin/build-slc-lib.sh, core/src/sphinx/coq.rst, core/src/sphinx/index.rst, core/src/sphinx/neon.rst
@vkuncak Any modification or addition you would like to see for the documentation?
=> Documentation for Coq and proofs

core/src/main/scala/stainless/extraction/termination/InductElimination.scala, frontends/benchmarks/typechecker/valid/Issue803.scala
=> Fix for issue 803: swap bitvector size and value

core/src/main/scala/stainless/ast/Deconstructors.scala, core/src/main/scala/stainless/ast/Definitions.scala, core/src/main/scala/stainless/extraction/imperative/EffectsChecker.scala, core/src/main/scala/stainless/solvers/InoxEncoder.scala, core/src/main/scala/stainless/utils/Serialization.scala, frontends/benchmarks/extraction/invalid/ImpureLazy.scala, frontends/benchmarks/extraction/invalid/ImpureLazy2.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
Add a `Lazy` flag to `Let` and make sure that such val's do no have side-effects.
=> Prevent lazy val's from having effects

core/src/main/scala/stainless/extraction/oo/TypeEncoding.scala
=> Fix type encoding erasing error[Nothing] to unit

core/src/sphinx/casestudies.rst, core/src/sphinx/index.rst, core/src/sphinx/purescala.rst
With suggestions from @OStevan (thanks!)
=> Documentation on '???' in abstract classes

core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala, core/src/main/scala/stainless/extraction/imperative/SymbolOps.scala
Fix for https://github.com/epfl-lara/stainless/issues/811
Is that ok?
=> Avoid infinite loop in isMutableClassType

core/src/main/scala/stainless/extraction/utils/ConcurrentCaches.scala, core/src/main/scala/stainless/frontend/SplitCallBack.scala
Fix https://github.com/epfl-lara/stainless/issues/514
=> Fix issue 514 where in watch mode some functions do not appear in reports

core/src/main/scala/stainless/frontend/ThreadedFrontend.scala
Fix https://github.com/epfl-lara/stainless/issues/501
=> Clear exceptions to avoid stale reporting in watch mode

core/src/main/scala/stainless/frontend/BatchedCallBack.scala, core/src/main/scala/stainless/frontend/SplitCallBack.scala, core/src/main/scala/stainless/utils/FileWatcher.scala
Fix https://github.com/epfl-lara/stainless/issues/496
=> Fix missing field error in watch mode

core/src/main/scala/stainless/utils/Serialization.scala
To find duplicates:
```bash
grep -Eoh '[0-9]{1,}' core/src/main/scala/stainless/utils/Serialization.scala | sort | uniq -c | grep -v "1 "
```
=> Remove duplicate serializations

build.sbt, core/src/main/scala/stainless/MainHelpers.scala, core/src/main/scala/stainless/frontend/BatchedCallBack.scala, core/src/main/scala/stainless/frontend/SplitCallBack.scala
Depends on https://github.com/epfl-lara/inox/pull/123/commits/693e26c481777805fc0d0ee708927155e5b3578c
=> Terminate before running the pipeline if there was an error

core/src/main/scala/stainless/extraction/innerfuns/FunctionClosure.scala
The filtering as implemented can remove useful conditions in the path when they don't directly refer to a free variable of the closure (but do so indirectly through another variable).
=> Remove filtering of path conditions in function closures

core/src/main/scala/stainless/MainHelpers.scala, core/src/main/scala/stainless/ast/Deconstructors.scala, core/src/main/scala/stainless/ast/Definitions.scala, core/src/main/scala/stainless/extraction/inlining/FunctionInlining.scala, core/src/main/scala/stainless/extraction/inlining/FunctionSpecialization.scala, core/src/main/scala/stainless/extraction/inlining/package.scala, core/src/main/scala/stainless/extraction/package.scala, core/src/main/scala/stainless/solvers/InoxEncoder.scala, core/src/main/scala/stainless/utils/Serialization.scala, frontends/benchmarks/extraction/valid/FunSpecialization1.scala, frontends/library/stainless/annotation/annotations.scala, frontends/library/stainless/lang/package.scala
=> Port FunctionSpecialization phase from imperative branch

build.sbt, core/src/main/scala/stainless/ast/ExprOps.scala, core/src/main/scala/stainless/extraction/imperative/Trees.scala, core/src/main/scala/stainless/extraction/innerclasses/ExprOps.scala, core/src/main/scala/stainless/extraction/innerfuns/Trees.scala, core/src/main/scala/stainless/extraction/methods/Trees.scala, core/src/main/scala/stainless/extraction/oo/Trees.scala, core/src/main/scala/stainless/extraction/throwing/Trees.scala, core/src/main/scala/stainless/genc/GenCComponent.scala, core/src/main/scala/stainless/transformers/Transformer.scala
Can be merged after https://github.com/epfl-lara/inox/pull/126 is merged
Hopefully I didn't introduce too many bugs here...
=> Adapt freshenLocals to new Inox API

RELEASE_NOTES.md, bin/external-tests.sh, build.sbt, core/src/main/scala/stainless/verification/TypeChecker.scala, core/src/main/scala/stainless/verification/TypeCheckerContext.scala, core/src/main/scala/stainless/verification/TypeCheckerUtils.scala, sbt-plugin/src/main/scala/ch/epfl/lara/sbt/stainless/StainlessPlugin.scala
* Fix nightly
* Release notes for Stainless version to 0.8.0
* Fix in type-checker VC generation for refinement types
=> Release notes for Stainless 0.8.0

core/src/main/scala/stainless/genc/phases/Scala2IRPhase.scala
=> Prevent name mangling for exported functions in GenC

.larabot.conf
Updating github users who can run larabot
=> update trusted for larabot

core/src/main/scala/stainless/extraction/package.scala
the phase was integrated in SizedADTExtraction
=> Remove size injection from help list

core/src/main/scala/stainless/verification/TypeChecker.scala
My solution with `TopLevelLets` wasn't good, because it wasn't going through `Let`'s inside conjuncts.
=> More filtering of unchecked expressions

build.sbt, core/src/main/scala/stainless/MainHelpers.scala, core/src/main/scala/stainless/Report.scala, core/src/main/scala/stainless/Reporter.scala
Fix https://github.com/epfl-lara/stainless/issues/960
Depends on https://github.com/epfl-lara/inox/pull/131
=> Propagate option optNoColors to Inox

core/src/main/scala/stainless/extraction/oo/TransformerWithType.scala, core/src/main/scala/stainless/genc/phases/Scala2IRPhase.scala, core/src/main/scala/stainless/verification/AssertionInjector.scala, core/src/main/scala/stainless/verification/TypeChecker.scala, core/src/sphinx/genc.rst, core/src/sphinx/purescala.rst, frontends/benchmarks/strictarithmetic/invalid/NarrowSigned1.scala, frontends/benchmarks/strictarithmetic/invalid/NarrowSigned2.scala, frontends/benchmarks/strictarithmetic/invalid/NarrowUnsigned.scala, frontends/benchmarks/strictarithmetic/invalid/SignedToUnsigned.scala, frontends/benchmarks/strictarithmetic/invalid/UnsignedToSigned.scala, frontends/benchmarks/strictarithmetic/valid/SignedUnsignedConversions.scala, frontends/benchmarks/verification/valid/MicroTests/BitVectors3.scala, frontends/library/stainless/math/BitVectors.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
=> Add more support for bitvector operations and documentation

core/src/main/scala/stainless/termination/SizeFunctions.scala
=> Fix typing error in #1003

core/src/main/scala/stainless/verification/VerificationChecker.scala
=> Fix timeouts being ignored for ADT invariants

core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala, core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala, core/src/main/scala/stainless/extraction/imperative/GhostChecker.scala, core/src/main/scala/stainless/extraction/imperative/ImperativeCleanup.scala, core/src/main/scala/stainless/extraction/imperative/ReturnElimination.scala, core/src/main/scala/stainless/extraction/imperative/Trees.scala, frontends/benchmarks/imperative/valid/SpecifySwap.scala, frontends/benchmarks/imperative/valid/Swap.scala, frontends/benchmarks/imperative/valid/Swap2.scala, frontends/library/stainless/lang/package.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/FragmentChecker.scala
I opened this draft PR to discuss https://github.com/epfl-lara/stainless/issues/943
I still need to add swaps between arrays and references, and between two references
=> Add support for Swap operation for array elements

core/src/main/scala/stainless/MainHelpers.scala, core/src/main/scala/stainless/extraction/inlining/FunctionInlining.scala, core/src/main/scala/stainless/termination/MeasureInference.scala, core/src/main/scala/stainless/verification/VerificationChecker.scala, core/src/main/scala/stainless/verification/VerificationComponent.scala
* Less duplication of verification conditions
* Less verbose
=> Minor fixes

core/src/main/scala/stainless/extraction/oo/Trees.scala
=> Fix pretty printing of InstanceOfPattern

core/src/main/scala/stainless/genc/CPrinter.scala, core/src/main/scala/stainless/termination/Strengthener.scala
Fix https://github.com/epfl-lara/stainless/issues/1034
=> Fix getSpec crash in MeasureInference

bin/package-standalone.sh
=> Fix terminal colors in package script.

core/src/main/scala/stainless/ast/ExprOps.scala, core/src/main/scala/stainless/genc/CAST.scala, core/src/main/scala/stainless/genc/CASTDependencies.scala, core/src/main/scala/stainless/genc/CPrinter.scala, core/src/main/scala/stainless/genc/GenerateCPhase.scala, core/src/main/scala/stainless/genc/LeonPhase.scala, core/src/main/scala/stainless/genc/ir/ClassLifter.scala, core/src/main/scala/stainless/genc/ir/IR.scala, core/src/main/scala/stainless/genc/ir/IRPrinter.scala, core/src/main/scala/stainless/genc/ir/Normaliser.scala, core/src/main/scala/stainless/genc/ir/Transformer.scala, core/src/main/scala/stainless/genc/ir/Visitor.scala, core/src/main/scala/stainless/genc/phases/IR2CPhase.scala, core/src/main/scala/stainless/genc/phases/Scala2IRPhase.scala, core/src/main/scala/stainless/genc/phases/package.scala, core/src/main/scala/stainless/termination/LoopProcessor.scala, core/src/main/scala/stainless/termination/MeasureInference.scala, core/src/main/scala/stainless/termination/SolverProvider.scala, core/src/main/scala/stainless/termination/Strengthener.scala, frontends/benchmarks/genc/FixedArray.scala, frontends/benchmarks/genc/ImageProcessing.scala
I'll add some documentation in the next PR
=> Add preliminary support for inlined arrays in GenC

core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala, core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala, core/src/main/scala/stainless/extraction/imperative/GhostChecker.scala, frontends/benchmarks/imperative/valid/MutableTuple.scala
Closes #1063.
- Add benchmark for tuple with mutable types
- Implement tuple field accessor
=> Support tuples with mutable types

core/src/main/scala/stainless/extraction/imperative/EffectsChecker.scala, core/src/main/scala/stainless/extraction/imperative/ReturnElimination.scala, core/src/main/scala/stainless/extraction/imperative/TransformerWithPC.scala, core/src/main/scala/stainless/extraction/imperative/TransformerWithType.scala, core/src/main/scala/stainless/extraction/imperative/Trees.scala, core/src/main/scala/stainless/extraction/xlang/TreeSanitizer.scala, core/src/main/scala/stainless/genc/phases/Scala2IRPhase.scala, frontends/benchmarks/imperative/valid/ReturnInWhile3.scala, frontends/library/stainless/lang/StaticChecks.scala, frontends/library/stainless/lang/package.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
This would be for invariants that hold except possibly after a return, as in the example:
https://github.com/epfl-lara/stainless/compare/master...jad-hamza:weak-invariant?expand=1#diff-55629b8363aa945eac95e724c9e0c143d6a3ec9acb36d5183ed377ad612d2203
Any thoughts?
=> Add weak invariants for while loops

core/src/main/scala/stainless/genc/CAST.scala, core/src/main/scala/stainless/genc/CPrinter.scala, core/src/main/scala/stainless/genc/ir/IR.scala, core/src/main/scala/stainless/genc/ir/IRPrinter.scala, core/src/main/scala/stainless/genc/ir/Normaliser.scala, core/src/main/scala/stainless/genc/ir/Transformer.scala, core/src/main/scala/stainless/genc/phases/IR2CPhase.scala, core/src/main/scala/stainless/genc/phases/Scala2IRPhase.scala, core/src/sphinx/genc.rst, frontends/benchmarks/verification/valid/MicroTests/BitVectors1.scala, frontends/library/stainless/math/BitVectors.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
* add bitwise negation to bitvectors library
* transform requires in exported functions to asserts
* add documentation for `@export`
=> Bitwise negation in bitvectors + transform requires in exported functions to asserts

core/src/main/scala/stainless/extraction/imperative/EffectsChecker.scala
thanks @samarion for catching the issue
=> Add missing traversals in effects checker

core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala, frontends/benchmarks/imperative/valid/Issue1097.scala
=> Fix issue #1097 where targets in one branch were discarded

build.sbt, core/src/main/scala/stainless/MainHelpers.scala, core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala, core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala, core/src/main/scala/stainless/extraction/inlining/FunctionInlining.scala, core/src/main/scala/stainless/genc/CPrinter.scala, core/src/main/scala/stainless/genc/ir/IR.scala, core/src/main/scala/stainless/genc/ir/Transformer.scala, core/src/main/scala/stainless/genc/phases/ComputeDependenciesPhase.scala, core/src/main/scala/stainless/genc/phases/ExtraOps.scala, core/src/main/scala/stainless/genc/phases/IR2CPhase.scala, core/src/main/scala/stainless/genc/phases/Scala2IRPhase.scala, core/src/main/scala/stainless/verification/AssertionInjector.scala, frontends/benchmarks/extraction/invalid/IllegalAliasing2.scala, frontends/benchmarks/imperative/valid/ArrayAccess.scala, frontends/benchmarks/imperative/valid/Issue1097.scala, frontends/benchmarks/imperative/valid/Issue1111.scala, frontends/benchmarks/imperative/valid/WrappedArray.scala
This is just a plain merge of `master` into `rust-interop` to get the fixes for #1097 and #1111.
=> Update Rust interop from master

core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala, core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala, frontends/benchmarks/imperative/valid/Issue1111b.scala, frontends/benchmarks/imperative/valid/Issue1111c.scala
cc @yannbolliger 
Fix #1111 (bis)
=> Add bindings when computing targets (bis)

core/src/main/scala/stainless/genc/CAST.scala, core/src/main/scala/stainless/genc/CASTDependencies.scala, core/src/main/scala/stainless/genc/CPrinter.scala, core/src/main/scala/stainless/genc/phases/IR2CPhase.scala, core/src/main/scala/stainless/genc/phases/Scala2IRPhase.scala, frontends/benchmarks/genc/ArgumentsEffects.scala, frontends/benchmarks/genc/FixedArray.scala, frontends/benchmarks/genc/Global.scala, frontends/benchmarks/genc/GlobalUninitialized.scala, frontends/benchmarks/genc/ImageProcessing.scala, frontends/benchmarks/genc/Nested.scala, frontends/benchmarks/genc/Normalisation.scala, frontends/benchmarks/genc/Pointer.scala, frontends/benchmarks/genc/Return.scala, frontends/benchmarks/genc/Unsigned.scala, frontends/benchmarks/imperative/valid/FindIndex.scala, frontends/library/stainless/io/StdOut.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/FragmentChecker.scala
Fix https://github.com/epfl-lara/stainless/issues/1117
=> Add pure attribute to pure functions

frontends/scalac/src/main/scala/stainless/frontends/scalac/GhostAccessRewriter.scala
Fix https://github.com/epfl-lara/stainless/issues/696 again (wasn't really fixed by #1119)
This should hopefully fix the nightly builds as well.
=> Fix ghost elimination for multiple parameter groups

core/src/main/scala/stainless/genc/CPrinter.scala, frontends/scalac/src/it/scala/stainless/termination/TerminationSuite.scala
Fix https://github.com/epfl-lara/stainless/issues/1202
=> Better header extraction in GenC cCode.function annotation

frontends/benchmarks/verification/invalid/LawsExampleInvalid.scala, frontends/benchmarks/verification/invalid/OOPSI.scala, frontends/benchmarks/verification/valid/LawsExample.scala
Example testcase why inheritance can be tricky
=> example with laws and dynamic dispatch

sbt-plugin/src/sbt-test/sbt-plugin/ghost/actor-tests/src/main/scala/Actors.scala, sbt-plugin/src/sbt-test/sbt-plugin/ghost/actor-tests/src/main/scala/Counter.scala
Note that since `scripted` is only run on nightly, we cannot see whether the tests actually succeed.
=> Reenable actors tests

core/src/main/scala/stainless/genc/CAST.scala, core/src/main/scala/stainless/genc/CASTDependencies.scala, core/src/main/scala/stainless/genc/CPrinter.scala, core/src/main/scala/stainless/genc/ir/ClassLifter.scala, core/src/main/scala/stainless/genc/ir/IR.scala, core/src/main/scala/stainless/genc/ir/IRPrinter.scala, core/src/main/scala/stainless/genc/ir/Normaliser.scala, core/src/main/scala/stainless/genc/ir/Referentiator.scala, core/src/main/scala/stainless/genc/ir/StructInliner.scala, core/src/main/scala/stainless/genc/ir/Transformer.scala, core/src/main/scala/stainless/genc/ir/Visitor.scala, core/src/main/scala/stainless/genc/phases/ExtraOps.scala, core/src/main/scala/stainless/genc/phases/IR2CPhase.scala, core/src/main/scala/stainless/genc/phases/Scala2IRPhase.scala, core/src/main/scala/stainless/genc/phases/TrimSymbols.scala, frontends/library/stainless/annotation/cCode.scala
This port PR #1207 (Add cCode.noMangling annotation and split defines into header and C files) to the main Scala 3 branch, and also fixes the following small mistake:
https://github.com/epfl-lara/stainless/pull/1233/files#diff-ab9720ee9e71db2b1bdea4600047edb645ce60feb28f2a644a42b16789b1d3abR672
=> Port PR #1207 to Scala 3

frontends/benchmarks/extraction/invalid/Initialization6.scala, frontends/benchmarks/termination/valid/CyclicFibStream.scala, frontends/benchmarks/termination/valid/CyclicHammingStream.scala, frontends/benchmarks/verification/valid/GodelNumbering.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/DottyCompiler.scala, frontends/scalac/src/it/scala/stainless/ScalacExtractionSuite.scala
Addresses https://github.com/epfl-lara/stainless/issues/1215
=> Pass the `-Ysafe-init` option to Dotty

core/src/main/scala/stainless/extraction/innerclasses/InnerClasses.scala, frontends/benchmarks/extraction/invalid/InnerClassesInvariants1.scala, frontends/benchmarks/extraction/invalid/InnerClassesInvariants2.scala, frontends/benchmarks/verification/invalid/InnerClassesInvariants.scala, frontends/benchmarks/verification/valid/InnerClassesInvariants.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
=> PC for local classes capturing variables

docs/RELEASE_NOTES.md
=> Update release notes

frontends/benchmarks/verification/invalid/i497.scala
=> Add regression test for #497

.gitattributes, core/src/main/scala/stainless/ast/SymbolOps.scala, core/src/main/scala/stainless/extraction/inlining/ChooseInjector.scala, core/src/main/scala/stainless/verification/AssertionInjector.scala, frontends/benchmarks/verification/invalid/i1295.scala
Fix #1295 though there may be other cases where VC position are missing.
=> Adding missing source info in some cases, and add `.gitattributes`

core/src/main/scala/stainless/MainHelpers.scala, core/src/main/scala/stainless/Report.scala, core/src/main/scala/stainless/extraction/xlang/PartialFunctions.scala, core/src/main/scala/stainless/transformers/LatticesSimplifier.scala, core/src/main/scala/stainless/transformers/lattices/Bland.scala, core/src/main/scala/stainless/transformers/lattices/Core.scala, core/src/main/scala/stainless/transformers/lattices/Definitions.scala, core/src/main/scala/stainless/transformers/lattices/OCBSL.scala, core/src/main/scala/stainless/transformers/lattices/OL.scala, core/src/main/scala/stainless/verification/VerificationCache.scala, core/src/main/scala/stainless/verification/VerificationChecker.scala
Note: the default simplifier remain the current one
=> Experimental integration of OL- and OCBSL- based simplifiers

sbt-plugin/project/build.properties, sbt-plugin/src/sbt-test/sbt-plugin/ghost/project/build.properties, sbt-plugin/src/sbt-test/sbt-plugin/ghost/test, sbt-plugin/src/sbt-test/sbt-plugin/simple/test
Sorry about this one, I've forgot about it!
=> Fix 'scripted' tests

core/src/main/scala/stainless/frontend/BatchedCallBack.scala, core/src/main/scala/stainless/frontend/SplitCallBack.scala, frontends/benchmarks/extraction/invalid/i1352.scala, frontends/benchmarks/extraction/valid/i1351.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/FragmentChecker.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/FragmentChecker.scala
Closes #1351, #1352, #1353
Opened the same day, closed the same day.
=> Fix #1351, #1352, #1353

build.sbt, frontends/benchmarks/verification/valid/ContMonad.scala, frontends/benchmarks/verification/valid/i1350a.scala, frontends/benchmarks/verification/valid/i1350b.scala, frontends/benchmarks/verification/valid/i1350c.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/ASTExtractors.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/CodeExtraction.scala, frontends/library/stainless/lang/StaticChecks.scala, frontends/library/stainless/lang/package.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
Closes #1350
Doing two separate things in a PR is not very clean (I can split them if desired)
=> Bump Inox and make ghost, assert and require arguments by-name

frontends/benchmarks/dotty-specific/valid/TestContext.scala, frontends/benchmarks/imperative/valid/Cached.scala, frontends/benchmarks/imperative/valid/Lambda3.scala
=> Add three tests

build.sbt
This ensures we get the correct directory when using Stainless as a dependency.
=> In build.sbt, use `baseDirectory.value` instead of `root.base`

build.sbt
This updates the Princess solver dependency.
=> Update Inox dependency

frontends/benchmarks/equivalence/boardgame/Candidate1.scala, frontends/benchmarks/equivalence/boardgame/Candidate2.scala, frontends/benchmarks/equivalence/boardgame/Candidate3.scala, frontends/benchmarks/equivalence/boardgame/Candidate4.scala, frontends/benchmarks/equivalence/boardgame/Model.scala, frontends/benchmarks/equivalence/boardgame/defs.scala, frontends/benchmarks/equivalence/cloudSculpting/Model.scala, frontends/benchmarks/equivalence/funnyarith1/Candidate.scala, frontends/benchmarks/equivalence/funnyarith1/Model.scala, frontends/benchmarks/equivalence/funnyarith1/defs.scala, frontends/benchmarks/equivalence/funnyarith2/Candidate.scala, frontends/benchmarks/equivalence/funnyarith2/Model.scala, frontends/benchmarks/equivalence/funnyarith2/defs.scala
If 1 gram of CO2 were to be captured every time I forget about the `scalac` frontend, all the cumulative CO2 emitted so far wouldn't be enough...
=> Scala 2 source compatible equivalence checking benchmarks

frontends/benchmarks/verification/invalid/Float8.scala, frontends/benchmarks/verification/invalid/PackedFloat8.scala, frontends/benchmarks/verification/valid/Float8.scala, frontends/benchmarks/verification/valid/PackedFloat8.scala, frontends/common/src/it/scala/stainless/termination/TerminationSuite.scala, frontends/common/src/it/scala/stainless/verification/VerificationSuite.scala
=> Add `Float8` benchmarks showing commutativity and disproving associativity

core/src/main/scala/stainless/extraction/oo/TypeOps.scala, frontends/benchmarks/extraction/valid/i1389.scala, frontends/benchmarks/extraction/valid/i1390.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
=> Fix #1389 and #1390

.larabot.conf, build.sbt, core/src/main/scala/stainless/codegen/CodeGeneration.scala, core/src/main/scala/stainless/codegen/CompilationUnit.scala, core/src/main/scala/stainless/evaluators/RecursiveEvaluator.scala, frontends/benchmarks/evaluators/adtFailure/ADTFailure.scala, frontends/benchmarks/evaluators/adtFailure/test_conf.json, frontends/benchmarks/evaluators/i1377/i1377.scala, frontends/benchmarks/evaluators/i1377/test_conf.json, frontends/benchmarks/evaluators/postFailure/PostFailure.scala, frontends/benchmarks/evaluators/postFailure/test_conf.json, frontends/benchmarks/evaluators/preFailure/PreFailure.scala, frontends/benchmarks/evaluators/preFailure/test_conf.json, frontends/common/src/it/scala/stainless/evaluators/EvaluatorComponentTest.scala
=> Update Inox and fix #1377

core/src/sphinx/equivalence.rst
Minor updates in the documentation to reflect the changes in the implementation of `equivchk`
=> Document the latest --equivchk

core/src/main/scala/stainless/Component.scala, core/src/main/scala/stainless/MainHelpers.scala, core/src/main/scala/stainless/equivchk/EquivalenceCheckingComponent.scala, core/src/main/scala/stainless/extraction/imperative/package.scala, core/src/main/scala/stainless/extraction/inlining/package.scala, core/src/main/scala/stainless/extraction/innerclasses/package.scala, core/src/main/scala/stainless/extraction/innerfuns/package.scala, core/src/main/scala/stainless/extraction/methods/package.scala, core/src/main/scala/stainless/extraction/oo/package.scala, core/src/main/scala/stainless/extraction/package.scala, core/src/main/scala/stainless/extraction/termination/package.scala, core/src/main/scala/stainless/extraction/trace/package.scala, core/src/main/scala/stainless/extraction/utils/NamedPipeline.scala, core/src/main/scala/stainless/extraction/xlang/package.scala, core/src/main/scala/stainless/frontend/BatchedCallBack.scala, core/src/main/scala/stainless/frontend/SplitCallBack.scala, core/src/main/scala/stainless/genc/GenCComponent.scala, core/src/main/scala/stainless/termination/MeasureInference.scala, core/src/main/scala/stainless/verification/VerificationComponent.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/DottyCompiler.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/ScalaCompiler.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/SimpleReporter.scala
* Indicates what part of Stainless is currently running (e.g. compilation, preprocessing, etc.)
* Indicates the pipeline phase currently running (e.g. `ValueClass`, the dreaded `AntiAliasing`, etc.)
* Hides pattern matching warning
=> Add more info messages

core/src/main/scala/stainless/frontend/FrontendFactory.scala
Allows for blank lines and "commented" lines that start with `#`.
Non-existing files are reported by the compiler (instead of mysteriously crashing).
=> Gracefully handle non-existing files in `libfiles.txt`

build.sbt
To include the improvement for `DependencyGraph#dependencies` added in https://github.com/epfl-lara/inox/pull/200
=> Bump Inox version

core/src/main/scala/stainless/extraction/oo/TransformerWithType.scala
=> Fix erroneous positions for some BV-related operations

.larabot.conf, build.sbt, frontends/common/src/it/scala/org/scalatest/FixedThreadPoolParallelExecution.scala, frontends/common/src/it/scala/stainless/ComponentTestSuite.scala, frontends/common/src/it/scala/stainless/equivchk/EquivChkSuite.scala, frontends/common/src/it/scala/stainless/evaluators/EvaluatorComponentTest.scala, frontends/common/src/it/scala/stainless/termination/TerminationSuite.scala, frontends/common/src/it/scala/stainless/verification/FullImperativeSuite.scala, frontends/common/src/it/scala/stainless/verification/ImperativeSuite.scala, frontends/common/src/it/scala/stainless/verification/StrictArithmeticSuite.scala, frontends/common/src/it/scala/stainless/verification/TerminationVerificationSuite.scala, frontends/common/src/it/scala/stainless/verification/UncheckedSuite.scala, frontends/common/src/it/scala/stainless/verification/VerificationComponentTestSuite.scala, frontends/common/src/it/scala/stainless/verification/VerificationSuite.scala, frontends/dotty/src/it/scala/stainless/verification/DottyVerificationSuite.scala
This introduces "per test" parallelism and should hopefully reduce testing time.
=> Improve integration tests parallelism

core/src/main/scala/stainless/ast/SymbolOps.scala, core/src/main/scala/stainless/verification/TypeChecker.scala, core/src/main/scala/stainless/verification/TypeCheckerContext.scala, core/src/main/scala/stainless/verification/TypeCheckerUtils.scala
=> Fix occasionally incorrect VC position

frontends/dotty/src/main/scala/stainless/frontends/dotc/ASTExtractors.scala, frontends/scalac/src/main/scala/stainless/frontends/scalac/ASTExtractors.scala
Before this PR, *all* annotations from the direct owner of a symbol were applied to that symbol. For instance, a `@library` object containing a function `f` would (correctly) get the `@library` flag, but not any of its inner functions (which is an incorrect behavior).
Furthermore, a function annotated with `@opaque` (incorrectly?) propagates this annotation to its direct inner functions.
This PR changes the following:
* Only the following annotations are propagated to the "children" of a symbol:
`stainless.annotation.ignore`
`stainless.annotation.library`
`stainless.annotation.extern`
`stainless.annotation.dropVCs`
`stainless.annotation.pure`
`stainless.annotation.wrapping`
`stainless.annotation.keep`
`stainless.annotation.keepFor`
`stainless.annotation.cCode.drop`
* These annotations are …
=> Change annotations propagation to consider transitive owners

frontends/benchmarks/dotty-specific/invalid/i1479.scala, frontends/benchmarks/dotty-specific/valid/i1479.scala, frontends/dotty/src/main/scala/stainless/frontends/dotc/ASTExtractors.scala
=> Do not treat inline methods or functions as ghost

.gitignore, bin/stainless-cli
Thanks to @vkuncak for fixing the original script!
=> Add `stainless-cli` script

README.md
Fixes #1650 by updating the CS550 switchtube links to mediaspace ones.
=> Fix video doc deadlinks in README.md
